// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file activities_tags.scailo.proto (package Scailo, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActivitiesTagsList, ActivitiesTagsServiceCountReq, ActivitiesTagsServiceCreateRequest, ActivitiesTagsServiceFilterReq, ActivitiesTagsServicePaginationReq, ActivitiesTagsServicePaginationResponse, ActivitiesTagsServiceSearchAllReq, ActivitiesTagsServiceUpdateRequest, ActivityTag } from "./activities_tags.scailo_pb.js";
import { ActiveStatus, CountInSLCStatusRequest, CountResponse, Identifier, IdentifierResponse, IdentifiersList, IdentifierUUID, IdentifierUUIDsList, IdentifierUUIDWithUserComment, StandardFile } from "./base.scailo_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 *
 * Describes the common methods applicable on each activity tag
 *
 * @generated from service Scailo.ActivitiesTagsService
 */
export const ActivitiesTagsService = {
  typeName: "Scailo.ActivitiesTagsService",
  methods: {
    /**
     * Create and send for verification
     *
     * @generated from rpc Scailo.ActivitiesTagsService.Create
     */
    create: {
      name: "Create",
      I: ActivitiesTagsServiceCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Saves a new record as a draft without triggering side effects.
     *
     * Use this method when you have incomplete information but wish to persist
     * the record for later completion. The record remains in a `DRAFT` state.
     *
     * **Note:** Some strict validation rules may be relaxed in the backend for drafts compared to `Create`.
     *
     * **Side Effects:**
     * - Generates a unique system UUID.
     * - Records an audit log for the "Draft" action.
     *
     * **Errors:**
     * - `INVALID_ARGUMENT`: If critical system fields are missing.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.Draft
     */
    draft: {
      name: "Draft",
      I: ActivitiesTagsServiceCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates an existing record that is currently in `DRAFT` status.
     *
     * This method allows modification of all primary attributes while the record is not yet verified.
     *
     * **Errors:**
     * - `FAILED_PRECONDITION`: If the record is not in a `DRAFT` state.
     * - `NOT_FOUND`: If the provided ID does not exist.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.DraftUpdate
     */
    draftUpdate: {
      name: "DraftUpdate",
      I: ActivitiesTagsServiceUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Submits a record in `DRAFT` or `REVISION` status for verification.
     *
     * This triggers the first stage of the approval workflow.
     *
     * **Status Transition:** -> `PREVERIFY`
     *
     * **Side Effects:**
     * - Notifies designated verifiers or approvers.
     * - Locks certain fields from being updated without returning to `REVISION`.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.SendForVerification
     */
    sendForVerification: {
      name: "SendForVerification",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Marks a record as verified, signaling that it is ready for final approval.
     *
     * **Status Transition:** -> `VERIFIED`
     *
     * **Side Effects:**
     * - Records the verifying user and timestamp in the audit logs.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.Verify
     */
    verify: {
      name: "Verify",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Officially approves the record.
     *
     * **Status Transition:** -> `STANDING`
     *
     * **Side Effects:**
     * - Finalizes the `final_ref_number`.
     * - Records the approver's identity and timestamp.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.Approve
     */
    approve: {
      name: "Approve",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sends the record back to the creator for corrections.
     *
     * Use this if details are incorrect or supporting documents (in the vault) are missing.
     *
     * **Status Transition:** -> `REVISION`
     *
     * **Side Effects:**
     * - Notifies the record creator that changes are required.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.SendForRevision
     */
    sendForRevision: {
      name: "SendForRevision",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a record that has been sent back for `REVISION`.
     *
     * **Side Effects:**
     * - Re-validates the updated fields.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.RevisionUpdate
     */
    revisionUpdate: {
      name: "RevisionUpdate",
      I: ActivitiesTagsServiceUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Temporarily halts processing of the record.
     *
     * **Status Transition:** -> `HALTED`
     *
     * @generated from rpc Scailo.ActivitiesTagsService.Halt
     */
    halt: {
      name: "Halt",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Permanently cancels the record.
     *
     * Records in this state are typically ignored.
     *
     * **Status Transition:** -> `DISCARDED`
     *
     * @generated from rpc Scailo.ActivitiesTagsService.Discard
     */
    discard: {
      name: "Discard",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Restores a previously `DISCARDED` or `HALTED` record.
     *
     * **Side Effects:**
     * - Moves the record back to `PREVERIFY` and sends for verification.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.Restore
     */
    restore: {
      name: "Restore",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds an audit comment to the record's history without changing its current lifecycle status.
     *
     * Send Email
     * rpc SendEmail (Identifier) returns (IdentifierResponse);
     *
     * @generated from rpc Scailo.ActivitiesTagsService.CommentAdd
     */
    commentAdd: {
      name: "CommentAdd",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a single record by its internal numeric ID. This operation is optimized for high-performance internal system logic and backend-to-backend communication
     *
     * @generated from rpc Scailo.ActivitiesTagsService.ViewByID
     */
    viewByID: {
      name: "ViewByID",
      I: Identifier,
      O: ActivityTag,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a single record by its globally unique UUID. This is intended for public-facing interfaces, since record identifiers aren't sequential and thus cannot be predicted.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.ViewByUUID
     */
    viewByUUID: {
      name: "ViewByUUID",
      I: IdentifierUUID,
      O: ActivityTag,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a record by ID excluding high-volume fields like logs for performance. This operation is optimized for high-performance internal system logic and backend-to-backend communication
     *
     * @generated from rpc Scailo.ActivitiesTagsService.ViewEssentialByID
     */
    viewEssentialByID: {
      name: "ViewEssentialByID",
      I: Identifier,
      O: ActivityTag,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a record by UUID excluding high-volume fields like logs. This is intended for public-facing interfaces, since record identifiers aren't sequential and thus cannot be predicted.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.ViewEssentialByUUID
     */
    viewEssentialByUUID: {
      name: "ViewEssentialByUUID",
      I: IdentifierUUID,
      O: ActivityTag,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a list of records matching the provided array of internal IDs.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.ViewFromIDs
     */
    viewFromIDs: {
      name: "ViewFromIDs",
      I: IdentifiersList,
      O: ActivitiesTagsList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns all records filtered by their active status.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.ViewAll
     */
    viewAll: {
      name: "ViewAll",
      I: ActiveStatus,
      O: ActivitiesTagsList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns all records belonging to a specific organization/entity UUID.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.ViewAllForEntityUUID
     */
    viewAllForEntityUUID: {
      name: "ViewAllForEntityUUID",
      I: IdentifierUUID,
      O: ActivitiesTagsList,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a paginated list of records based on status, sort keys, and offsets.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.ViewWithPagination
     */
    viewWithPagination: {
      name: "ViewWithPagination",
      I: ActivitiesTagsServicePaginationReq,
      O: ActivitiesTagsServicePaginationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Performs a free-text search across records using a search key.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.SearchAll
     */
    searchAll: {
      name: "SearchAll",
      I: ActivitiesTagsServiceSearchAllReq,
      O: ActivitiesTagsList,
      kind: MethodKind.Unary,
    },
    /**
     * Performs a high-granularity search based on multiple specific field filters.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.Filter
     */
    filter: {
      name: "Filter",
      I: ActivitiesTagsServiceFilterReq,
      O: ActivitiesTagsList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the total number of records currently in a specific lifecycle status.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.CountInStatus
     */
    countInStatus: {
      name: "CountInStatus",
      I: CountInSLCStatusRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the total count of records matching the given complex filter criteria.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.Count
     */
    count: {
      name: "Count",
      I: ActivitiesTagsServiceCountReq,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CSV operations
     * Download the CSV file that consists of the list of records according to the given filter request. The same file could also be used as a template for uploading records
     *
     * @generated from rpc Scailo.ActivitiesTagsService.DownloadAsCSV
     */
    downloadAsCSV: {
      name: "DownloadAsCSV",
      I: ActivitiesTagsServiceFilterReq,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
    /**
     * Bulk imports records from a provided CSV file.
     * Behavior:
     * - Deduplication: Skips entries where the `code` already exists in the system.
     * - Atomicity: This is an "all-or-nothing" operation; if any part of the
     *   import fails, no changes are committed.
     * - Idempotency: Multiple calls with the same CSV result in the same state.
     * Returns a list of UUIDs for all successfully processed or existing records.
     *
     * @generated from rpc Scailo.ActivitiesTagsService.ImportFromCSV
     */
    importFromCSV: {
      name: "ImportFromCSV",
      I: StandardFile,
      O: IdentifierUUIDsList,
      kind: MethodKind.Unary,
    },
  }
} as const;

