// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file attendances.scailo.proto (package Scailo, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Attendance, AttendancesList, AttendancesServiceCountReq, AttendancesServiceCreateRequest, AttendancesServiceFilterReq, AttendancesServiceImageEntryRequest, AttendancesServiceImageExitRequest, AttendancesServicePaginationReq, AttendancesServicePaginationResponse, AttendancesServiceSearchAllReq, AttendancesServiceUpdateRequest } from "./attendances.scailo_pb.js";
import { ActiveStatus, BooleanResponse, CountInSLCStatusRequest, CountResponse, GPSCoordinatesResponse, Identifier, IdentifierResponse, IdentifiersList, IdentifierUUID, IdentifierUUIDWithUserComment, ImageResponse, StandardFile } from "./base.scailo_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { VaultFolderAttachRequest } from "./vault_folders.scailo_pb.js";
import { MagicLink, MagicLinksServiceCreateRequestForSpecificResource } from "./magic_links.scailo_pb.js";

/**
 *
 * Describes the common methods applicable on each attendance
 *
 * @generated from service Scailo.AttendancesService
 */
export const AttendancesService = {
  typeName: "Scailo.AttendancesService",
  methods: {
    /**
     * Create and send for verification
     *
     * @generated from rpc Scailo.AttendancesService.Create
     */
    create: {
      name: "Create",
      I: AttendancesServiceCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Saves a new record as a draft without triggering side effects.
     *
     * Use this method when you have incomplete information but wish to persist
     * the record for later completion. The record remains in a `DRAFT` state.
     *
     * **Note:** Some strict validation rules may be relaxed in the backend for drafts compared to `Create`.
     *
     * **Side Effects:**
     * - Generates a unique system UUID.
     * - Records an audit log for the "Draft" action.
     *
     * **Errors:**
     * - `INVALID_ARGUMENT`: If critical system fields are missing.
     *
     * @generated from rpc Scailo.AttendancesService.Draft
     */
    draft: {
      name: "Draft",
      I: AttendancesServiceCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates an existing record that is currently in `DRAFT` status.
     *
     * This method allows modification of all primary attributes while the record is not yet verified.
     *
     * **Errors:**
     * - `FAILED_PRECONDITION`: If the record is not in a `DRAFT` state.
     * - `NOT_FOUND`: If the provided ID does not exist.
     *
     * @generated from rpc Scailo.AttendancesService.DraftUpdate
     */
    draftUpdate: {
      name: "DraftUpdate",
      I: AttendancesServiceUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Submits a record in `DRAFT` or `REVISION` status for verification.
     *
     * This triggers the first stage of the approval workflow.
     *
     * **Status Transition:** -> `PREVERIFY`
     *
     * **Side Effects:**
     * - Notifies designated verifiers or approvers.
     * - Locks certain fields from being updated without returning to `REVISION`.
     *
     * @generated from rpc Scailo.AttendancesService.SendForVerification
     */
    sendForVerification: {
      name: "SendForVerification",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Marks a record as verified, signaling that it is ready for final approval.
     *
     * **Status Transition:** -> `VERIFIED`
     *
     * **Side Effects:**
     * - Records the verifying user and timestamp in the audit logs.
     *
     * @generated from rpc Scailo.AttendancesService.Verify
     */
    verify: {
      name: "Verify",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Officially approves the record.
     *
     * **Status Transition:** -> `STANDING`
     *
     * **Side Effects:**
     * - Finalizes the `final_ref_number`.
     * - Records the approver's identity and timestamp.
     *
     * @generated from rpc Scailo.AttendancesService.Approve
     */
    approve: {
      name: "Approve",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sends the record back to the creator for corrections.
     *
     * Use this if details are incorrect or supporting documents (in the vault) are missing.
     *
     * **Status Transition:** -> `REVISION`
     *
     * **Side Effects:**
     * - Notifies the record creator that changes are required.
     *
     * @generated from rpc Scailo.AttendancesService.SendForRevision
     */
    sendForRevision: {
      name: "SendForRevision",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a record that has been sent back for `REVISION`.
     *
     * **Side Effects:**
     * - Re-validates the updated fields.
     *
     * @generated from rpc Scailo.AttendancesService.RevisionUpdate
     */
    revisionUpdate: {
      name: "RevisionUpdate",
      I: AttendancesServiceUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Temporarily halts processing of the record.
     *
     * **Status Transition:** -> `HALTED`
     *
     * @generated from rpc Scailo.AttendancesService.Halt
     */
    halt: {
      name: "Halt",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Permanently cancels the record.
     *
     * Records in this state are typically ignored.
     *
     * **Status Transition:** -> `DISCARDED`
     *
     * @generated from rpc Scailo.AttendancesService.Discard
     */
    discard: {
      name: "Discard",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Restores a previously `DISCARDED` or `HALTED` record.
     *
     * **Side Effects:**
     * - Moves the record back to `PREVERIFY` and sends for verification.
     *
     * @generated from rpc Scailo.AttendancesService.Restore
     */
    restore: {
      name: "Restore",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Marks the record as finalized and fully processed.
     *
     * **Status Transition:** -> `COMPLETED`
     *
     * **Side Effects:**
     * - Locks the record from further modification.
     *
     * @generated from rpc Scailo.AttendancesService.Complete
     */
    complete: {
      name: "Complete",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a new record based on an existing one (cloning).
     *
     * This is useful for repeating records or correcting finalized records by starting fresh.
     *
     * @generated from rpc Scailo.AttendancesService.Repeat
     */
    repeat: {
      name: "Repeat",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds an audit comment to the record's history without changing its current lifecycle status.
     *
     * Send Email
     * rpc SendEmail (Identifier) returns (IdentifierResponse);
     *
     * @generated from rpc Scailo.AttendancesService.CommentAdd
     */
    commentAdd: {
      name: "CommentAdd",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Attaches a specified folder directly to a record without requiring a full revision workflow.
     *
     * This is a convenience API designed to bypass the traditional multi-step modification lifecycle
     * (e.g., creating a revision, updating data, submitting for verification, and awaiting approval).
     * It allows for the immediate, single-step association of a vault folder.
     *
     * **Side Effects & Lifecycle:**
     * * The overall status of the record remains unchanged.
     * * The record's modification timestamp is automatically updated to the current time.
     * * An entry is appended to the record's audit log tracking this attachment.
     *
     * @generated from rpc Scailo.AttendancesService.AttachVaultFolder
     */
    attachVaultFolder: {
      name: "AttachVaultFolder",
      I: VaultFolderAttachRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Generates a magic link for temporary, authenticated access to the resource.
     *
     * This enables non-system users (or users without active sessions) to view specific details.
     *
     * @generated from rpc Scailo.AttendancesService.CreateMagicLink
     */
    createMagicLink: {
      name: "CreateMagicLink",
      I: MagicLinksServiceCreateRequestForSpecificResource,
      O: MagicLink,
      kind: MethodKind.Unary,
    },
    /**
     * Store entry time
     *
     * @generated from rpc Scailo.AttendancesService.RecordImageEntry
     */
    recordImageEntry: {
      name: "RecordImageEntry",
      I: AttendancesServiceImageEntryRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Store exit time
     *
     * @generated from rpc Scailo.AttendancesService.RecordImageExit
     */
    recordImageExit: {
      name: "RecordImageExit",
      I: AttendancesServiceImageExitRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a single record by its internal numeric ID. This operation is optimized for high-performance internal system logic and backend-to-backend communication
     *
     * @generated from rpc Scailo.AttendancesService.ViewByID
     */
    viewByID: {
      name: "ViewByID",
      I: Identifier,
      O: Attendance,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a single record by its globally unique UUID. This is intended for public-facing interfaces, since record identifiers aren't sequential and thus cannot be predicted.
     *
     * @generated from rpc Scailo.AttendancesService.ViewByUUID
     */
    viewByUUID: {
      name: "ViewByUUID",
      I: IdentifierUUID,
      O: Attendance,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a record by ID excluding high-volume fields like logs for performance. This operation is optimized for high-performance internal system logic and backend-to-backend communication
     *
     * @generated from rpc Scailo.AttendancesService.ViewEssentialByID
     */
    viewEssentialByID: {
      name: "ViewEssentialByID",
      I: Identifier,
      O: Attendance,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a record by UUID excluding high-volume fields like logs. This is intended for public-facing interfaces, since record identifiers aren't sequential and thus cannot be predicted.
     *
     * @generated from rpc Scailo.AttendancesService.ViewEssentialByUUID
     */
    viewEssentialByUUID: {
      name: "ViewEssentialByUUID",
      I: IdentifierUUID,
      O: Attendance,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a list of records matching the provided array of internal IDs.
     *
     * @generated from rpc Scailo.AttendancesService.ViewFromIDs
     */
    viewFromIDs: {
      name: "ViewFromIDs",
      I: IdentifiersList,
      O: AttendancesList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns all records filtered by their active status.
     *
     * @generated from rpc Scailo.AttendancesService.ViewAll
     */
    viewAll: {
      name: "ViewAll",
      I: ActiveStatus,
      O: AttendancesList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns all records belonging to a specific organization/entity UUID.
     *
     * @generated from rpc Scailo.AttendancesService.ViewAllForEntityUUID
     */
    viewAllForEntityUUID: {
      name: "ViewAllForEntityUUID",
      I: IdentifierUUID,
      O: AttendancesList,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a paginated list of records based on status, sort keys, and offsets.
     *
     * @generated from rpc Scailo.AttendancesService.ViewWithPagination
     */
    viewWithPagination: {
      name: "ViewWithPagination",
      I: AttendancesServicePaginationReq,
      O: AttendancesServicePaginationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View entry image for attendance UUID
     *
     * @generated from rpc Scailo.AttendancesService.ViewEntryImage
     */
    viewEntryImage: {
      name: "ViewEntryImage",
      I: IdentifierUUID,
      O: ImageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Confirm that the entry image of the given attendance UUID belongs to the user
     *
     * @generated from rpc Scailo.AttendancesService.ConfirmEntryImage
     */
    confirmEntryImage: {
      name: "ConfirmEntryImage",
      I: IdentifierUUID,
      O: BooleanResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View exit image for attendance UUID
     *
     * @generated from rpc Scailo.AttendancesService.ViewExitImage
     */
    viewExitImage: {
      name: "ViewExitImage",
      I: IdentifierUUID,
      O: ImageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Confirm that the exit image of the given attendance UUID belongs to the user
     *
     * @generated from rpc Scailo.AttendancesService.ConfirmExitImage
     */
    confirmExitImage: {
      name: "ConfirmExitImage",
      I: IdentifierUUID,
      O: BooleanResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View entry GPS coordinates for attendance UUID
     *
     * @generated from rpc Scailo.AttendancesService.ViewEntryGPSCoordinates
     */
    viewEntryGPSCoordinates: {
      name: "ViewEntryGPSCoordinates",
      I: IdentifierUUID,
      O: GPSCoordinatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View exit GPS coordinates for attendance UUID
     *
     * @generated from rpc Scailo.AttendancesService.ViewExitGPSCoordinates
     */
    viewExitGPSCoordinates: {
      name: "ViewExitGPSCoordinates",
      I: IdentifierUUID,
      O: GPSCoordinatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View entry GPS static image from Google Maps
     *
     * @generated from rpc Scailo.AttendancesService.ViewEntryGPSStaticImage
     */
    viewEntryGPSStaticImage: {
      name: "ViewEntryGPSStaticImage",
      I: IdentifierUUID,
      O: ImageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View exit GPS static image from Google Maps
     *
     * @generated from rpc Scailo.AttendancesService.ViewExitGPSStaticImage
     */
    viewExitGPSStaticImage: {
      name: "ViewExitGPSStaticImage",
      I: IdentifierUUID,
      O: ImageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View the open attendance for a user (with the given identifier), if available. Returns an empty instance if no attendance is available
     *
     * @generated from rpc Scailo.AttendancesService.ViewOpenAttendanceForUser
     */
    viewOpenAttendanceForUser: {
      name: "ViewOpenAttendanceForUser",
      I: Identifier,
      O: Attendance,
      kind: MethodKind.Unary,
    },
    /**
     * Performs a free-text search across records using a search key.
     *
     * @generated from rpc Scailo.AttendancesService.SearchAll
     */
    searchAll: {
      name: "SearchAll",
      I: AttendancesServiceSearchAllReq,
      O: AttendancesList,
      kind: MethodKind.Unary,
    },
    /**
     * Performs a high-granularity search based on multiple specific field filters.
     *
     * @generated from rpc Scailo.AttendancesService.Filter
     */
    filter: {
      name: "Filter",
      I: AttendancesServiceFilterReq,
      O: AttendancesList,
      kind: MethodKind.Unary,
    },
    /**
     * Checks if a user (with the given identifier) has an open attendance (attendance with only entry and no exit)
     *
     * @generated from rpc Scailo.AttendancesService.EmployeeHasOpenAttendance
     */
    employeeHasOpenAttendance: {
      name: "EmployeeHasOpenAttendance",
      I: Identifier,
      O: BooleanResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the total number of records currently in a specific lifecycle status.
     *
     * @generated from rpc Scailo.AttendancesService.CountInStatus
     */
    countInStatus: {
      name: "CountInStatus",
      I: CountInSLCStatusRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the total count of records matching the given complex filter criteria.
     *
     * @generated from rpc Scailo.AttendancesService.Count
     */
    count: {
      name: "Count",
      I: AttendancesServiceCountReq,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CSV operations
     * Download the CSV file that consists of the list of records according to the given filter request. The same file could also be used as a template for uploading records
     *
     * @generated from rpc Scailo.AttendancesService.DownloadAsCSV
     */
    downloadAsCSV: {
      name: "DownloadAsCSV",
      I: AttendancesServiceFilterReq,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
  }
} as const;

