// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file sales_orders.scailo.proto (package Scailo, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SalesOrder, SalesOrderAncillaryParameters, SalesOrderBillingStatistics, SalesOrderContact, SalesOrderContactsList, SalesOrderInventoryMatchList, SalesOrderInventoryStatistics, SalesOrderItem, SalesOrderItemHistoryRequest, SalesOrderItemProspectiveInfoRequest, SalesOrderItemsList, SalesOrderItemsSearchRequest, SalesOrderPriceMatchList, SalesOrderReference, SalesOrderReferencesList, SalesOrdersList, SalesOrdersServiceAutofillRequest, SalesOrdersServiceContactCreateRequest, SalesOrdersServiceCountReq, SalesOrdersServiceCreateRequest, SalesOrdersServiceFilterReq, SalesOrdersServiceItemCreateRequest, SalesOrdersServiceItemSpecificationsUpdateRequest, SalesOrdersServiceItemTermsUpdateRequest, SalesOrdersServiceItemUpdateRequest, SalesOrdersServiceMultipleItemsCreateRequest, SalesOrdersServicePaginatedItemsResponse, SalesOrdersServicePaginationReq, SalesOrdersServicePaginationResponse, SalesOrdersServiceReferenceCreateRequest, SalesOrdersServiceSearchAllReq, SalesOrdersServiceUpdateRequest } from "./sales_orders.scailo_pb.js";
import { ActiveStatus, AmendmentLogsList, BooleanResponse, CountInSLCStatusRequest, CountResponse, Empty, Identifier, IdentifierResponse, IdentifiersList, IdentifierUUID, IdentifierUUIDWithFile, IdentifierUUIDWithUserComment, IdentifierWithEmailAttributes, IdentifierWithSearchKey, IdentifierWithUserComment, PriceResponse, ReorderItemsRequest, RepeatWithDeliveryDate, SimpleSearchReq, StandardFile, SumResponse } from "./base.scailo_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { MagicLink, MagicLinksServiceCreateRequestForSpecificResource } from "./magic_links.scailo_pb.js";
import { FamiliesList, FilterFamiliesReqForIdentifier } from "./families.scailo_pb.js";

/**
 *
 * Describes the common methods applicable on each sales order
 *
 * @generated from service Scailo.SalesOrdersService
 */
export const SalesOrdersService = {
  typeName: "Scailo.SalesOrdersService",
  methods: {
    /**
     * Create and send for verification
     *
     * @generated from rpc Scailo.SalesOrdersService.Create
     */
    create: {
      name: "Create",
      I: SalesOrdersServiceCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Saves a new record as a draft without triggering side effects.
     *
     * Use this method when you have incomplete information but wish to persist
     * the record for later completion. The record remains in a `DRAFT` state.
     *
     * **Note:** Some strict validation rules may be relaxed in the backend for drafts compared to `Create`.
     *
     * **Side Effects:**
     * - Generates a unique system UUID.
     * - Records an audit log for the "Draft" action.
     *
     * **Errors:**
     * - `INVALID_ARGUMENT`: If critical system fields are missing.
     *
     * @generated from rpc Scailo.SalesOrdersService.Draft
     */
    draft: {
      name: "Draft",
      I: SalesOrdersServiceCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates an existing record that is currently in `DRAFT` status.
     *
     * This method allows modification of all primary attributes while the record is not yet verified.
     *
     * **Errors:**
     * - `FAILED_PRECONDITION`: If the record is not in a `DRAFT` state.
     * - `NOT_FOUND`: If the provided ID does not exist.
     *
     * @generated from rpc Scailo.SalesOrdersService.DraftUpdate
     */
    draftUpdate: {
      name: "DraftUpdate",
      I: SalesOrdersServiceUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Submits a record in `DRAFT` or `REVISION` status for verification.
     *
     * This triggers the first stage of the approval workflow.
     *
     * **Status Transition:** -> `PREVERIFY`
     *
     * **Side Effects:**
     * - Notifies designated verifiers or approvers.
     * - Locks certain fields from being updated without returning to `REVISION`.
     *
     * @generated from rpc Scailo.SalesOrdersService.SendForVerification
     */
    sendForVerification: {
      name: "SendForVerification",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Marks a record as verified, signaling that it is ready for final approval.
     *
     * **Status Transition:** -> `VERIFIED`
     *
     * **Side Effects:**
     * - Records the verifying user and timestamp in the audit logs.
     *
     * @generated from rpc Scailo.SalesOrdersService.Verify
     */
    verify: {
      name: "Verify",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Officially approves the record.
     *
     * **Status Transition:** -> `STANDING`
     *
     * **Side Effects:**
     * - Finalizes the `final_ref_number`.
     * - Records the approver's identity and timestamp.
     *
     * @generated from rpc Scailo.SalesOrdersService.Approve
     */
    approve: {
      name: "Approve",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sends the record back to the creator for corrections.
     *
     * Use this if details are incorrect or supporting documents (in the vault) are missing.
     *
     * **Status Transition:** -> `REVISION`
     *
     * **Side Effects:**
     * - Notifies the record creator that changes are required.
     *
     * @generated from rpc Scailo.SalesOrdersService.SendForRevision
     */
    sendForRevision: {
      name: "SendForRevision",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a record that has been sent back for `REVISION`.
     *
     * **Side Effects:**
     * - Re-validates the updated fields.
     *
     * @generated from rpc Scailo.SalesOrdersService.RevisionUpdate
     */
    revisionUpdate: {
      name: "RevisionUpdate",
      I: SalesOrdersServiceUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Temporarily halts processing of the record.
     *
     * **Status Transition:** -> `HALTED`
     *
     * @generated from rpc Scailo.SalesOrdersService.Halt
     */
    halt: {
      name: "Halt",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Permanently cancels the record.
     *
     * Records in this state are typically ignored.
     *
     * **Status Transition:** -> `DISCARDED`
     *
     * @generated from rpc Scailo.SalesOrdersService.Discard
     */
    discard: {
      name: "Discard",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Restores a previously `DISCARDED` or `HALTED` record.
     *
     * **Side Effects:**
     * - Moves the record back to `PREVERIFY` and sends for verification.
     *
     * @generated from rpc Scailo.SalesOrdersService.Restore
     */
    restore: {
      name: "Restore",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Marks the record as finalized and fully processed.
     *
     * **Status Transition:** -> `COMPLETED`
     *
     * **Side Effects:**
     * - Locks the record from further modification.
     *
     * @generated from rpc Scailo.SalesOrdersService.Complete
     */
    complete: {
      name: "Complete",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Repeat
     *
     * @generated from rpc Scailo.SalesOrdersService.Repeat
     */
    repeat: {
      name: "Repeat",
      I: RepeatWithDeliveryDate,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reopen
     *
     * @generated from rpc Scailo.SalesOrdersService.Reopen
     */
    reopen: {
      name: "Reopen",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds an audit comment to the record's history without changing its current lifecycle status.
     *
     * @generated from rpc Scailo.SalesOrdersService.CommentAdd
     */
    commentAdd: {
      name: "CommentAdd",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Send Email
     *
     * @generated from rpc Scailo.SalesOrdersService.SendEmail
     */
    sendEmail: {
      name: "SendEmail",
      I: IdentifierWithEmailAttributes,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Autofill the sales order
     *
     * @generated from rpc Scailo.SalesOrdersService.Autofill
     */
    autofill: {
      name: "Autofill",
      I: SalesOrdersServiceAutofillRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Amend the sales order and send for revision
     *
     * @generated from rpc Scailo.SalesOrdersService.Amend
     */
    amend: {
      name: "Amend",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Generates a magic link for temporary, authenticated access to the resource.
     *
     * This enables non-system users (or users without active sessions) to view specific details.
     *
     * @generated from rpc Scailo.SalesOrdersService.CreateMagicLink
     */
    createMagicLink: {
      name: "CreateMagicLink",
      I: MagicLinksServiceCreateRequestForSpecificResource,
      O: MagicLink,
      kind: MethodKind.Unary,
    },
    /**
     * Add multiple items to a sales order
     *
     * @generated from rpc Scailo.SalesOrdersService.AddMultipleSalesOrderItems
     */
    addMultipleSalesOrderItems: {
      name: "AddMultipleSalesOrderItems",
      I: SalesOrdersServiceMultipleItemsCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Add an item to a sales order
     *
     * @generated from rpc Scailo.SalesOrdersService.AddSalesOrderItem
     */
    addSalesOrderItem: {
      name: "AddSalesOrderItem",
      I: SalesOrdersServiceItemCreateRequest,
      O: IdentifiersList,
      kind: MethodKind.Unary,
    },
    /**
     * Modify an item in a sales order
     *
     * @generated from rpc Scailo.SalesOrdersService.ModifySalesOrderItem
     */
    modifySalesOrderItem: {
      name: "ModifySalesOrderItem",
      I: SalesOrdersServiceItemUpdateRequest,
      O: IdentifiersList,
      kind: MethodKind.Unary,
    },
    /**
     * Update Price, Discount, Tax Group, Delivery Date and Specifications of an item in a sales order. This can safely be done even after the item may have been dispatched
     *
     * @generated from rpc Scailo.SalesOrdersService.UpdateSalesOrderItemTerms
     */
    updateSalesOrderItemTerms: {
      name: "UpdateSalesOrderItemTerms",
      I: SalesOrdersServiceItemTermsUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update specifications of an item in a sales order
     *
     * @generated from rpc Scailo.SalesOrdersService.UpdateSalesOrderItemSpecifications
     */
    updateSalesOrderItemSpecifications: {
      name: "UpdateSalesOrderItemSpecifications",
      I: SalesOrdersServiceItemSpecificationsUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Approve an item in a sales order
     *
     * @generated from rpc Scailo.SalesOrdersService.ApproveSalesOrderItem
     */
    approveSalesOrderItem: {
      name: "ApproveSalesOrderItem",
      I: IdentifierWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete an item in a sales order
     *
     * @generated from rpc Scailo.SalesOrdersService.DeleteSalesOrderItem
     */
    deleteSalesOrderItem: {
      name: "DeleteSalesOrderItem",
      I: IdentifierWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reorder items in a sales order
     *
     * @generated from rpc Scailo.SalesOrdersService.ReorderSalesOrderItems
     */
    reorderSalesOrderItems: {
      name: "ReorderSalesOrderItems",
      I: ReorderItemsRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View Sales Order Item by ID
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewSalesOrderItemByID
     */
    viewSalesOrderItemByID: {
      name: "ViewSalesOrderItemByID",
      I: Identifier,
      O: SalesOrderItem,
      kind: MethodKind.Unary,
    },
    /**
     * View Sales Order Item's price after factoring in the discount
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewSalesOrderItemPrice
     */
    viewSalesOrderItemPrice: {
      name: "ViewSalesOrderItemPrice",
      I: SalesOrderItemProspectiveInfoRequest,
      O: PriceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View approved sales order items for given sales order ID
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewApprovedSalesOrderItems
     */
    viewApprovedSalesOrderItems: {
      name: "ViewApprovedSalesOrderItems",
      I: IdentifierWithSearchKey,
      O: SalesOrderItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * View unapproved sales order items for given sales order ID
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewUnapprovedSalesOrderItems
     */
    viewUnapprovedSalesOrderItems: {
      name: "ViewUnapprovedSalesOrderItems",
      I: IdentifierWithSearchKey,
      O: SalesOrderItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * View the history of the sales order item
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewSalesOrderItemHistory
     */
    viewSalesOrderItemHistory: {
      name: "ViewSalesOrderItemHistory",
      I: SalesOrderItemHistoryRequest,
      O: SalesOrderItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * View approved sales order items for given sales order ID with pagination
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewPaginatedApprovedSalesOrderItems
     */
    viewPaginatedApprovedSalesOrderItems: {
      name: "ViewPaginatedApprovedSalesOrderItems",
      I: SalesOrderItemsSearchRequest,
      O: SalesOrdersServicePaginatedItemsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View unapproved sales order items for given sales order ID with pagination
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewPaginatedUnapprovedSalesOrderItems
     */
    viewPaginatedUnapprovedSalesOrderItems: {
      name: "ViewPaginatedUnapprovedSalesOrderItems",
      I: SalesOrderItemsSearchRequest,
      O: SalesOrdersServicePaginatedItemsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Search through sales order items with pagination
     *
     * @generated from rpc Scailo.SalesOrdersService.SearchItemsWithPagination
     */
    searchItemsWithPagination: {
      name: "SearchItemsWithPagination",
      I: SalesOrderItemsSearchRequest,
      O: SalesOrdersServicePaginatedItemsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CSV operations
     * Download the CSV file with the associated line items. The same file could then be used to upload line items.
     *
     * @generated from rpc Scailo.SalesOrdersService.DownloadItemsAsCSV
     */
    downloadItemsAsCSV: {
      name: "DownloadItemsAsCSV",
      I: IdentifierUUID,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
    /**
     * Download the CSV template that could be used to upload items
     *
     * @generated from rpc Scailo.SalesOrdersService.DownloadItemsTemplateAsCSV
     */
    downloadItemsTemplateAsCSV: {
      name: "DownloadItemsTemplateAsCSV",
      I: Empty,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
    /**
     * Upload items using a CSV file. This is an idempotent operation. All the existing items are deleted before adding the items from the file.
     *
     * @generated from rpc Scailo.SalesOrdersService.UploadSalesOrderItems
     */
    uploadSalesOrderItems: {
      name: "UploadSalesOrderItems",
      I: IdentifierUUIDWithFile,
      O: IdentifiersList,
      kind: MethodKind.Unary,
    },
    /**
     * Add a contact
     *
     * @generated from rpc Scailo.SalesOrdersService.AddSalesOrderContact
     */
    addSalesOrderContact: {
      name: "AddSalesOrderContact",
      I: SalesOrdersServiceContactCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Approve a contact
     *
     * @generated from rpc Scailo.SalesOrdersService.ApproveSalesOrderContact
     */
    approveSalesOrderContact: {
      name: "ApproveSalesOrderContact",
      I: IdentifierWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete a contact
     *
     * @generated from rpc Scailo.SalesOrdersService.DeleteSalesOrderContact
     */
    deleteSalesOrderContact: {
      name: "DeleteSalesOrderContact",
      I: IdentifierWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View a contact for the given ID
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewSalesOrderContactByID
     */
    viewSalesOrderContactByID: {
      name: "ViewSalesOrderContactByID",
      I: Identifier,
      O: SalesOrderContact,
      kind: MethodKind.Unary,
    },
    /**
     * View all contacts for given sales order UUID
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewSalesOrderContacts
     */
    viewSalesOrderContacts: {
      name: "ViewSalesOrderContacts",
      I: IdentifierUUID,
      O: SalesOrderContactsList,
      kind: MethodKind.Unary,
    },
    /**
     * Add a reference
     *
     * @generated from rpc Scailo.SalesOrdersService.AddSalesOrderReference
     */
    addSalesOrderReference: {
      name: "AddSalesOrderReference",
      I: SalesOrdersServiceReferenceCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Approve a reference
     *
     * @generated from rpc Scailo.SalesOrdersService.ApproveSalesOrderReference
     */
    approveSalesOrderReference: {
      name: "ApproveSalesOrderReference",
      I: IdentifierWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete a reference
     *
     * @generated from rpc Scailo.SalesOrdersService.DeleteSalesOrderReference
     */
    deleteSalesOrderReference: {
      name: "DeleteSalesOrderReference",
      I: IdentifierWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View a reference for the given ID
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewSalesOrderReferenceByID
     */
    viewSalesOrderReferenceByID: {
      name: "ViewSalesOrderReferenceByID",
      I: Identifier,
      O: SalesOrderReference,
      kind: MethodKind.Unary,
    },
    /**
     * View all references for given sales order ID
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewSalesOrderReferences
     */
    viewSalesOrderReferences: {
      name: "ViewSalesOrderReferences",
      I: Identifier,
      O: SalesOrderReferencesList,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a single record by its internal numeric ID. This operation is optimized for high-performance internal system logic and backend-to-backend communication
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewByID
     */
    viewByID: {
      name: "ViewByID",
      I: Identifier,
      O: SalesOrder,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a single record by its globally unique UUID. This is intended for public-facing interfaces, since record identifiers aren't sequential and thus cannot be predicted.
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewByUUID
     */
    viewByUUID: {
      name: "ViewByUUID",
      I: IdentifierUUID,
      O: SalesOrder,
      kind: MethodKind.Unary,
    },
    /**
     * View by Reference ID (returns the latest record in case of duplicates)
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewByReferenceID
     */
    viewByReferenceID: {
      name: "ViewByReferenceID",
      I: SimpleSearchReq,
      O: SalesOrder,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a record by ID excluding high-volume fields like logs for performance. This operation is optimized for high-performance internal system logic and backend-to-backend communication
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewEssentialByID
     */
    viewEssentialByID: {
      name: "ViewEssentialByID",
      I: Identifier,
      O: SalesOrder,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a record by UUID excluding high-volume fields like logs. This is intended for public-facing interfaces, since record identifiers aren't sequential and thus cannot be predicted.
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewEssentialByUUID
     */
    viewEssentialByUUID: {
      name: "ViewEssentialByUUID",
      I: IdentifierUUID,
      O: SalesOrder,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a list of records matching the provided array of internal IDs.
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewFromIDs
     */
    viewFromIDs: {
      name: "ViewFromIDs",
      I: IdentifiersList,
      O: SalesOrdersList,
      kind: MethodKind.Unary,
    },
    /**
     * View the ancillary parameters (UUIDs of the internal references) by UUID
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewAncillaryParametersByUUID
     */
    viewAncillaryParametersByUUID: {
      name: "ViewAncillaryParametersByUUID",
      I: IdentifierUUID,
      O: SalesOrderAncillaryParameters,
      kind: MethodKind.Unary,
    },
    /**
     * Returns all records filtered by their active status.
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewAll
     */
    viewAll: {
      name: "ViewAll",
      I: ActiveStatus,
      O: SalesOrdersList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns all records belonging to a specific organization/entity UUID.
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewAllForEntityUUID
     */
    viewAllForEntityUUID: {
      name: "ViewAllForEntityUUID",
      I: IdentifierUUID,
      O: SalesOrdersList,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a paginated list of records based on status, sort keys, and offsets.
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewWithPagination
     */
    viewWithPagination: {
      name: "ViewWithPagination",
      I: SalesOrdersServicePaginationReq,
      O: SalesOrdersServicePaginationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View all the amendments made
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewAmendments
     */
    viewAmendments: {
      name: "ViewAmendments",
      I: Identifier,
      O: AmendmentLogsList,
      kind: MethodKind.Unary,
    },
    /**
     * View Inventory Statistics of Sales Order
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewInventoryStatistics
     */
    viewInventoryStatistics: {
      name: "ViewInventoryStatistics",
      I: IdentifierUUID,
      O: SalesOrderInventoryStatistics,
      kind: MethodKind.Unary,
    },
    /**
     * View Billing Statistics of Sales Order
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewBillingStatistics
     */
    viewBillingStatistics: {
      name: "ViewBillingStatistics",
      I: IdentifierUUID,
      O: SalesOrderBillingStatistics,
      kind: MethodKind.Unary,
    },
    /**
     * View Inventory Match of all the families within a Sales Order
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewInventoryMatch
     */
    viewInventoryMatch: {
      name: "ViewInventoryMatch",
      I: IdentifierUUID,
      O: SalesOrderInventoryMatchList,
      kind: MethodKind.Unary,
    },
    /**
     * View Price Match of all the families within a Sales Order (between the sales order, and the corresponding sales invoices, and any corresponding credit notes)
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewPriceMatch
     */
    viewPriceMatch: {
      name: "ViewPriceMatch",
      I: IdentifierUUID,
      O: SalesOrderPriceMatchList,
      kind: MethodKind.Unary,
    },
    /**
     * View prospective families for the given sales order
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewProspectiveFamilies
     */
    viewProspectiveFamilies: {
      name: "ViewProspectiveFamilies",
      I: IdentifierWithSearchKey,
      O: FamiliesList,
      kind: MethodKind.Unary,
    },
    /**
     * Filter prospective families for the record represented by the given UUID identifier
     *
     * @generated from rpc Scailo.SalesOrdersService.FilterProspectiveFamilies
     */
    filterProspectiveFamilies: {
      name: "FilterProspectiveFamilies",
      I: FilterFamiliesReqForIdentifier,
      O: FamiliesList,
      kind: MethodKind.Unary,
    },
    /**
     * View prospective sales order item info for the given family ID and sales order ID
     *
     * @generated from rpc Scailo.SalesOrdersService.ViewProspectiveSalesOrderItem
     */
    viewProspectiveSalesOrderItem: {
      name: "ViewProspectiveSalesOrderItem",
      I: SalesOrderItemProspectiveInfoRequest,
      O: SalesOrdersServiceItemCreateRequest,
      kind: MethodKind.Unary,
    },
    /**
     * Checks if the record is downloadable (checks if the custom download function has been implemented)
     *
     * @generated from rpc Scailo.SalesOrdersService.IsDownloadable
     */
    isDownloadable: {
      name: "IsDownloadable",
      I: IdentifierUUID,
      O: BooleanResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Download sales order with the given IdentifierUUID (can be used to allow public downloads)
     *
     * @generated from rpc Scailo.SalesOrdersService.DownloadByUUID
     */
    downloadByUUID: {
      name: "DownloadByUUID",
      I: IdentifierUUID,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
    /**
     * Performs a free-text search across records using a search key.
     *
     * @generated from rpc Scailo.SalesOrdersService.SearchAll
     */
    searchAll: {
      name: "SearchAll",
      I: SalesOrdersServiceSearchAllReq,
      O: SalesOrdersList,
      kind: MethodKind.Unary,
    },
    /**
     * Performs a high-granularity search based on multiple specific field filters.
     *
     * @generated from rpc Scailo.SalesOrdersService.Filter
     */
    filter: {
      name: "Filter",
      I: SalesOrdersServiceFilterReq,
      O: SalesOrdersList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the total number of records currently in a specific lifecycle status.
     *
     * @generated from rpc Scailo.SalesOrdersService.CountInStatus
     */
    countInStatus: {
      name: "CountInStatus",
      I: CountInSLCStatusRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the total count of records matching the given complex filter criteria.
     *
     * @generated from rpc Scailo.SalesOrdersService.Count
     */
    count: {
      name: "Count",
      I: SalesOrdersServiceCountReq,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the sum of the total value of all the records that match the given criteria
     *
     * @generated from rpc Scailo.SalesOrdersService.AccruedValue
     */
    accruedValue: {
      name: "AccruedValue",
      I: SalesOrdersServiceCountReq,
      O: SumResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CSV operations
     * Download the CSV file that consists of the list of records according to the given filter request. The same file could also be used as a template for uploading records
     *
     * @generated from rpc Scailo.SalesOrdersService.DownloadAsCSV
     */
    downloadAsCSV: {
      name: "DownloadAsCSV",
      I: SalesOrdersServiceFilterReq,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
  }
} as const;

