// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file skills_groups.scailo.proto (package Scailo, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SkillGroup, SkillGroupItem, SkillGroupItemHistoryRequest, SkillsGroupsItemsList, SkillsGroupsList, SkillsGroupsServiceCountReq, SkillsGroupsServiceCreateRequest, SkillsGroupsServiceFilterReq, SkillsGroupsServiceItemCreateRequest, SkillsGroupsServiceItemUpdateRequest, SkillsGroupsServicePaginationReq, SkillsGroupsServicePaginationResponse, SkillsGroupsServiceSearchAllReq, SkillsGroupsServiceUpdateRequest } from "./skills_groups.scailo_pb.js";
import { ActiveStatus, CloneRequest, CountInSLCStatusRequest, CountResponse, Empty, Identifier, IdentifierResponse, IdentifiersList, IdentifierUUID, IdentifierUUIDsList, IdentifierUUIDWithFile, IdentifierUUIDWithUserComment, IdentifierWithSearchKey, IdentifierWithUserComment, ReorderItemsRequest, SimpleSearchReq, StandardFile } from "./base.scailo_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { VaultFolderAttachRequest } from "./vault_folders.scailo_pb.js";

/**
 *
 * Describes the common methods applicable on each skill group
 *
 * @generated from service Scailo.SkillsGroupsService
 */
export const SkillsGroupsService = {
  typeName: "Scailo.SkillsGroupsService",
  methods: {
    /**
     * Create and send for verification
     *
     * @generated from rpc Scailo.SkillsGroupsService.Create
     */
    create: {
      name: "Create",
      I: SkillsGroupsServiceCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Saves a new record as a draft without triggering side effects.
     *
     * Use this method when you have incomplete information but wish to persist
     * the record for later completion. The record remains in a `DRAFT` state.
     *
     * **Note:** Some strict validation rules may be relaxed in the backend for drafts compared to `Create`.
     *
     * **Side Effects:**
     * - Generates a unique system UUID.
     * - Records an audit log for the "Draft" action.
     *
     * **Errors:**
     * - `INVALID_ARGUMENT`: If critical system fields are missing.
     *
     * @generated from rpc Scailo.SkillsGroupsService.Draft
     */
    draft: {
      name: "Draft",
      I: SkillsGroupsServiceCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates an existing record that is currently in `DRAFT` status.
     *
     * This method allows modification of all primary attributes while the record is not yet verified.
     *
     * **Errors:**
     * - `FAILED_PRECONDITION`: If the record is not in a `DRAFT` state.
     * - `NOT_FOUND`: If the provided ID does not exist.
     *
     * @generated from rpc Scailo.SkillsGroupsService.DraftUpdate
     */
    draftUpdate: {
      name: "DraftUpdate",
      I: SkillsGroupsServiceUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Submits a record in `DRAFT` or `REVISION` status for verification.
     *
     * This triggers the first stage of the approval workflow.
     *
     * **Status Transition:** -> `PREVERIFY`
     *
     * **Side Effects:**
     * - Notifies designated verifiers or approvers.
     * - Locks certain fields from being updated without returning to `REVISION`.
     *
     * @generated from rpc Scailo.SkillsGroupsService.SendForVerification
     */
    sendForVerification: {
      name: "SendForVerification",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Marks a record as verified, signaling that it is ready for final approval.
     *
     * **Status Transition:** -> `VERIFIED`
     *
     * **Side Effects:**
     * - Records the verifying user and timestamp in the audit logs.
     *
     * @generated from rpc Scailo.SkillsGroupsService.Verify
     */
    verify: {
      name: "Verify",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Officially approves the record.
     *
     * **Status Transition:** -> `STANDING`
     *
     * **Side Effects:**
     * - Finalizes the `final_ref_number`.
     * - Records the approver's identity and timestamp.
     *
     * @generated from rpc Scailo.SkillsGroupsService.Approve
     */
    approve: {
      name: "Approve",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sends the record back to the creator for corrections.
     *
     * Use this if details are incorrect or supporting documents (in the vault) are missing.
     *
     * **Status Transition:** -> `REVISION`
     *
     * **Side Effects:**
     * - Notifies the record creator that changes are required.
     *
     * @generated from rpc Scailo.SkillsGroupsService.SendForRevision
     */
    sendForRevision: {
      name: "SendForRevision",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a record that has been sent back for `REVISION`.
     *
     * **Side Effects:**
     * - Re-validates the updated fields.
     *
     * @generated from rpc Scailo.SkillsGroupsService.RevisionUpdate
     */
    revisionUpdate: {
      name: "RevisionUpdate",
      I: SkillsGroupsServiceUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Temporarily halts processing of the record.
     *
     * **Status Transition:** -> `HALTED`
     *
     * @generated from rpc Scailo.SkillsGroupsService.Halt
     */
    halt: {
      name: "Halt",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Permanently cancels the record.
     *
     * Records in this state are typically ignored.
     *
     * **Status Transition:** -> `DISCARDED`
     *
     * @generated from rpc Scailo.SkillsGroupsService.Discard
     */
    discard: {
      name: "Discard",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Restores a previously `DISCARDED` or `HALTED` record.
     *
     * **Side Effects:**
     * - Moves the record back to `PREVERIFY` and sends for verification.
     *
     * @generated from rpc Scailo.SkillsGroupsService.Restore
     */
    restore: {
      name: "Restore",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Marks the record as finalized and fully processed.
     *
     * **Status Transition:** -> `COMPLETED`
     *
     * **Side Effects:**
     * - Locks the record from further modification.
     *
     * @generated from rpc Scailo.SkillsGroupsService.Complete
     */
    complete: {
      name: "Complete",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a new record based on an existing one (cloning).
     *
     * This is useful for repeating records or correcting finalized records by starting fresh.
     *
     * @generated from rpc Scailo.SkillsGroupsService.Repeat
     */
    repeat: {
      name: "Repeat",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reopens a finalized or closed record for further modifications.
     *
     * **Status Transition:** -> `REVISION`
     *
     * **Side Effects:**
     * - Unlocks the record to allow edits.
     * - Logs the required user comment into the audit trail for compliance tracking.
     *
     * @generated from rpc Scailo.SkillsGroupsService.Reopen
     */
    reopen: {
      name: "Reopen",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds an audit comment to the record's history without changing its current lifecycle status.
     *
     * Send Email
     * rpc SendEmail (IdentifierWithEmailAttributes) returns (IdentifierResponse);
     *
     * @generated from rpc Scailo.SkillsGroupsService.CommentAdd
     */
    commentAdd: {
      name: "CommentAdd",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Attaches a specified folder directly to a record without requiring a full revision workflow.
     *
     * This is a convenience API designed to bypass the traditional multi-step modification lifecycle
     * (e.g., creating a revision, updating data, submitting for verification, and awaiting approval).
     * It allows for the immediate, single-step association of a vault folder.
     *
     * **Side Effects & Lifecycle:**
     * * The overall status of the record remains unchanged.
     * * The record's modification timestamp is automatically updated to the current time.
     * * An entry is appended to the record's audit log tracking this attachment.
     *
     * @generated from rpc Scailo.SkillsGroupsService.AttachVaultFolder
     */
    attachVaultFolder: {
      name: "AttachVaultFolder",
      I: VaultFolderAttachRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Initiates the creation of a new record by duplicating the structural properties of an existing record.
     *
     * **Side Effects:**
     * - Provisions a new record populated with the metadata and configurations of the source record.
     * - Does not clone operational transactions or historical logs of the source.
     * - Appends an audit trail entry tracking the cloning operation and justification.
     *
     * @generated from rpc Scailo.SkillsGroupsService.Clone
     */
    clone: {
      name: "Clone",
      I: CloneRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Add a param to a skill group
     *
     * @generated from rpc Scailo.SkillsGroupsService.AddSkillGroupItem
     */
    addSkillGroupItem: {
      name: "AddSkillGroupItem",
      I: SkillsGroupsServiceItemCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Modify a param in a skill group
     *
     * @generated from rpc Scailo.SkillsGroupsService.ModifySkillGroupItem
     */
    modifySkillGroupItem: {
      name: "ModifySkillGroupItem",
      I: SkillsGroupsServiceItemUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Approve a param in a skill group
     *
     * @generated from rpc Scailo.SkillsGroupsService.ApproveSkillGroupItem
     */
    approveSkillGroupItem: {
      name: "ApproveSkillGroupItem",
      I: IdentifierWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete a param in a skill group
     *
     * @generated from rpc Scailo.SkillsGroupsService.DeleteSkillGroupItem
     */
    deleteSkillGroupItem: {
      name: "DeleteSkillGroupItem",
      I: IdentifierWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reorder params in a skill group
     *
     * @generated from rpc Scailo.SkillsGroupsService.ReorderSkillGroupItems
     */
    reorderSkillGroupItems: {
      name: "ReorderSkillGroupItems",
      I: ReorderItemsRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View Skill Group Item by ID
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewSkillGroupItemByID
     */
    viewSkillGroupItemByID: {
      name: "ViewSkillGroupItemByID",
      I: Identifier,
      O: SkillGroupItem,
      kind: MethodKind.Unary,
    },
    /**
     * View approved skill group params for given skill group ID
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewApprovedSkillGroupItems
     */
    viewApprovedSkillGroupItems: {
      name: "ViewApprovedSkillGroupItems",
      I: IdentifierWithSearchKey,
      O: SkillsGroupsItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * View unapproved skill group params for given skill group ID
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewUnapprovedSkillGroupItems
     */
    viewUnapprovedSkillGroupItems: {
      name: "ViewUnapprovedSkillGroupItems",
      I: IdentifierWithSearchKey,
      O: SkillsGroupsItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * View the history of the skill group item
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewSkillGroupItemHistory
     */
    viewSkillGroupItemHistory: {
      name: "ViewSkillGroupItemHistory",
      I: SkillGroupItemHistoryRequest,
      O: SkillsGroupsItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * CSV operations
     * Download the CSV file with the associated line items. The same file could then be used to upload line items.
     *
     * @generated from rpc Scailo.SkillsGroupsService.DownloadItemsAsCSV
     */
    downloadItemsAsCSV: {
      name: "DownloadItemsAsCSV",
      I: IdentifierUUID,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
    /**
     * Download the CSV template that could be used to upload items
     *
     * @generated from rpc Scailo.SkillsGroupsService.DownloadItemsTemplateAsCSV
     */
    downloadItemsTemplateAsCSV: {
      name: "DownloadItemsTemplateAsCSV",
      I: Empty,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
    /**
     * Upload items using a CSV file. This is an idempotent operation. All the existing items are deleted before adding the items from the file.
     *
     * @generated from rpc Scailo.SkillsGroupsService.UploadSkillGroupItems
     */
    uploadSkillGroupItems: {
      name: "UploadSkillGroupItems",
      I: IdentifierUUIDWithFile,
      O: IdentifiersList,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a single record by its internal numeric ID. This operation is optimized for high-performance internal system logic and backend-to-backend communication
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewByID
     */
    viewByID: {
      name: "ViewByID",
      I: Identifier,
      O: SkillGroup,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a single record by its globally unique UUID. This is intended for public-facing interfaces, since record identifiers aren't sequential and thus cannot be predicted.
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewByUUID
     */
    viewByUUID: {
      name: "ViewByUUID",
      I: IdentifierUUID,
      O: SkillGroup,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a single record via the assigned internal code. In case duplicates are found, this method retrieves the latest record.
     *
     * **Note:** High-volume compliance data, audit records, and system logs are excluded from the response payload.
     *
     * **Errors:**
     * - `NOT_FOUND`: If the provided internal code does not exist.
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewByCode
     */
    viewByCode: {
      name: "ViewByCode",
      I: SimpleSearchReq,
      O: SkillGroup,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a record by ID excluding high-volume fields like logs for performance. This operation is optimized for high-performance internal system logic and backend-to-backend communication
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewEssentialByID
     */
    viewEssentialByID: {
      name: "ViewEssentialByID",
      I: Identifier,
      O: SkillGroup,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a record by UUID excluding high-volume fields like logs. This is intended for public-facing interfaces, since record identifiers aren't sequential and thus cannot be predicted.
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewEssentialByUUID
     */
    viewEssentialByUUID: {
      name: "ViewEssentialByUUID",
      I: IdentifierUUID,
      O: SkillGroup,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a list of records matching the provided array of internal IDs.
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewFromIDs
     */
    viewFromIDs: {
      name: "ViewFromIDs",
      I: IdentifiersList,
      O: SkillsGroupsList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns all records filtered by their active status.
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewAll
     */
    viewAll: {
      name: "ViewAll",
      I: ActiveStatus,
      O: SkillsGroupsList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns all records belonging to a specific organization/entity UUID.
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewAllForEntityUUID
     */
    viewAllForEntityUUID: {
      name: "ViewAllForEntityUUID",
      I: IdentifierUUID,
      O: SkillsGroupsList,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a paginated list of records based on status, sort keys, and offsets.
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewWithPagination
     */
    viewWithPagination: {
      name: "ViewWithPagination",
      I: SkillsGroupsServicePaginationReq,
      O: SkillsGroupsServicePaginationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View the latest skill group for a role (denoted by the given identifier)
     *
     * @generated from rpc Scailo.SkillsGroupsService.ViewForRoleID
     */
    viewForRoleID: {
      name: "ViewForRoleID",
      I: Identifier,
      O: SkillGroup,
      kind: MethodKind.Unary,
    },
    /**
     * Performs a free-text search across records using a search key.
     *
     * @generated from rpc Scailo.SkillsGroupsService.SearchAll
     */
    searchAll: {
      name: "SearchAll",
      I: SkillsGroupsServiceSearchAllReq,
      O: SkillsGroupsList,
      kind: MethodKind.Unary,
    },
    /**
     * Performs a high-granularity search based on multiple specific field filters.
     *
     * @generated from rpc Scailo.SkillsGroupsService.Filter
     */
    filter: {
      name: "Filter",
      I: SkillsGroupsServiceFilterReq,
      O: SkillsGroupsList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the total number of records currently in a specific lifecycle status.
     *
     * @generated from rpc Scailo.SkillsGroupsService.CountInStatus
     */
    countInStatus: {
      name: "CountInStatus",
      I: CountInSLCStatusRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the total count of records matching the given complex filter criteria.
     *
     * @generated from rpc Scailo.SkillsGroupsService.Count
     */
    count: {
      name: "Count",
      I: SkillsGroupsServiceCountReq,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CSV operations
     * Download the CSV file that consists of the list of records according to the given filter request. The same file could also be used as a template for uploading records
     *
     * @generated from rpc Scailo.SkillsGroupsService.DownloadAsCSV
     */
    downloadAsCSV: {
      name: "DownloadAsCSV",
      I: SkillsGroupsServiceFilterReq,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
    /**
     * Bulk imports records from a provided CSV file.
     * Behavior:
     * - Deduplication: Skips entries where the `code` already exists in the system.
     * - Atomicity: This is an "all-or-nothing" operation; if any part of the
     *   import fails, no changes are committed.
     * - Idempotency: Multiple calls with the same CSV result in the same state.
     * Returns a list of UUIDs for all successfully processed or existing records.
     *
     * @generated from rpc Scailo.SkillsGroupsService.ImportFromCSV
     */
    importFromCSV: {
      name: "ImportFromCSV",
      I: StandardFile,
      O: IdentifierUUIDsList,
      kind: MethodKind.Unary,
    },
  }
} as const;

