// @generated by protoc-gen-es v1.5.1 with parameter "target=ts"
// @generated from file transactional_emails.scailo.proto (package Scailo, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { BOOL_FILTER, EmployeeMetadata, SORT_ORDER } from "./base.scailo_pb.js";

/**
 *
 * Describes the available sort keys for retrieving transactional emails
 *
 * @generated from enum Scailo.TRANSACTIONAL_EMAIL_SORT_KEY
 */
export enum TRANSACTIONAL_EMAIL_SORT_KEY {
  /**
   * Fetch ordered results by id
   *
   * @generated from enum value: TRANSACTIONAL_EMAIL_SORT_KEY_ID_UNSPECIFIED = 0;
   */
  TRANSACTIONAL_EMAIL_SORT_KEY_ID_UNSPECIFIED = 0,

  /**
   * Fetch ordered results by the creation timestamp
   *
   * @generated from enum value: TRANSACTIONAL_EMAIL_SORT_KEY_CREATED_AT = 1;
   */
  TRANSACTIONAL_EMAIL_SORT_KEY_CREATED_AT = 1,

  /**
   * Fetch ordered results by the modified timestamp
   *
   * @generated from enum value: TRANSACTIONAL_EMAIL_SORT_KEY_MODIFIED_AT = 2;
   */
  TRANSACTIONAL_EMAIL_SORT_KEY_MODIFIED_AT = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(TRANSACTIONAL_EMAIL_SORT_KEY)
proto3.util.setEnumType(TRANSACTIONAL_EMAIL_SORT_KEY, "Scailo.TRANSACTIONAL_EMAIL_SORT_KEY", [
  { no: 0, name: "TRANSACTIONAL_EMAIL_SORT_KEY_ID_UNSPECIFIED" },
  { no: 1, name: "TRANSACTIONAL_EMAIL_SORT_KEY_CREATED_AT" },
  { no: 2, name: "TRANSACTIONAL_EMAIL_SORT_KEY_MODIFIED_AT" },
]);

/**
 *
 * Describes the necessary data structure during creation of a transactional email
 *
 * @generated from message Scailo.TransactionalEmailsServiceCreateRequest
 */
export class TransactionalEmailsServiceCreateRequest extends Message<TransactionalEmailsServiceCreateRequest> {
  /**
   *
   * @optional
   *
   * @description The globally unique identifier for the Organization or Business Entity.
   *
   * @example "550e8400-e29b-41d4-a716-446655440000"
   *
   * @regex ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
   *
   * @format If provided, must be a valid v4 UUID in canonical hyphenated form.
   *
   * @generated from field: string entity_uuid = 1;
   */
  entityUuid = "";

  /**
   *
   * @optional
   *
   * @description Audit log comment or justification for creating this record. This is stored in the record's history for compliance purposes.
   *
   * @example "This is a comment for audit purposes."
   *
   * @regex .*
   *
   * @format May contain any UTF-8 characters or be left empty.
   *
   * @generated from field: string user_comment = 2;
   */
  userComment = "";

  /**
   * Stores the name of the sender
   *
   * @generated from field: string sender_name = 10;
   */
  senderName = "";

  /**
   * Stores the title of the transactional email
   *
   * @generated from field: string title = 11;
   */
  title = "";

  /**
   * Stores the email address to which the reply could be sent
   *
   * @generated from field: string reply_to = 12;
   */
  replyTo = "";

  /**
   * Stores the subject of the transactional email
   *
   * @generated from field: string subject = 13;
   */
  subject = "";

  /**
   * Stores the content of the transactional email
   *
   * @generated from field: string content = 14;
   */
  content = "";

  /**
   * The list of recipients
   *
   * @generated from field: repeated Scailo.TransactionalEmailsServiceAddRecipientRequest recipients = 30;
   */
  recipients: TransactionalEmailsServiceAddRecipientRequest[] = [];

  /**
   * The list of attachments
   *
   * @generated from field: repeated Scailo.TransactionalEmailsServiceAddAttachmentRequest attachments = 40;
   */
  attachments: TransactionalEmailsServiceAddAttachmentRequest[] = [];

  constructor(data?: PartialMessage<TransactionalEmailsServiceCreateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailsServiceCreateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entity_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_comment", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "sender_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "reply_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 30, name: "recipients", kind: "message", T: TransactionalEmailsServiceAddRecipientRequest, repeated: true },
    { no: 40, name: "attachments", kind: "message", T: TransactionalEmailsServiceAddAttachmentRequest, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailsServiceCreateRequest {
    return new TransactionalEmailsServiceCreateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceCreateRequest {
    return new TransactionalEmailsServiceCreateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceCreateRequest {
    return new TransactionalEmailsServiceCreateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailsServiceCreateRequest | PlainMessage<TransactionalEmailsServiceCreateRequest> | undefined, b: TransactionalEmailsServiceCreateRequest | PlainMessage<TransactionalEmailsServiceCreateRequest> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailsServiceCreateRequest, a, b);
  }
}

/**
 *
 * Describes the data structure of each transactional email on the platform
 *
 * @generated from message Scailo.TransactionalEmail
 */
export class TransactionalEmail extends Message<TransactionalEmail> {
  /**
   *
   * @description The organization's globally unique identifier.
   *
   * @example "550e8400-e29b-41d4-a716-446655440000"
   *
   * @generated from field: string entity_uuid = 1;
   */
  entityUuid = "";

  /**
   * Stores the metadata of this resource
   *
   * @generated from field: Scailo.EmployeeMetadata metadata = 2;
   */
  metadata?: EmployeeMetadata;

  /**
   * Stores the name of the sender
   *
   * @generated from field: string sender_name = 10;
   */
  senderName = "";

  /**
   * Stores the title of the transactional email
   *
   * @generated from field: string title = 11;
   */
  title = "";

  /**
   * Stores the email address to which the reply could be sent
   *
   * @generated from field: string reply_to = 12;
   */
  replyTo = "";

  /**
   * Stores the subject of the transactional email
   *
   * @generated from field: string subject = 13;
   */
  subject = "";

  /**
   * Stores the content of the transactional email
   *
   * @generated from field: string content = 14;
   */
  content = "";

  /**
   * Stores the tracking URL of the transactional email
   *
   * @generated from field: string tracking_url = 20;
   */
  trackingUrl = "";

  constructor(data?: PartialMessage<TransactionalEmail>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmail";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entity_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "metadata", kind: "message", T: EmployeeMetadata },
    { no: 10, name: "sender_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "reply_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 20, name: "tracking_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmail {
    return new TransactionalEmail().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmail {
    return new TransactionalEmail().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmail {
    return new TransactionalEmail().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmail | PlainMessage<TransactionalEmail> | undefined, b: TransactionalEmail | PlainMessage<TransactionalEmail> | undefined): boolean {
    return proto3.util.equals(TransactionalEmail, a, b);
  }
}

/**
 *
 * Describes the data structure that stores a list of transactional emails
 *
 * @generated from message Scailo.TransactionalEmailsList
 */
export class TransactionalEmailsList extends Message<TransactionalEmailsList> {
  /**
   * List of transactional emails
   *
   * @generated from field: repeated Scailo.TransactionalEmail list = 1;
   */
  list: TransactionalEmail[] = [];

  constructor(data?: PartialMessage<TransactionalEmailsList>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailsList";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: TransactionalEmail, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailsList {
    return new TransactionalEmailsList().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailsList {
    return new TransactionalEmailsList().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailsList {
    return new TransactionalEmailsList().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailsList | PlainMessage<TransactionalEmailsList> | undefined, b: TransactionalEmailsList | PlainMessage<TransactionalEmailsList> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailsList, a, b);
  }
}

/**
 *
 * Describes the data structure that responds to a pagination request
 *
 * @generated from message Scailo.TransactionalEmailPaginationResp
 */
export class TransactionalEmailPaginationResp extends Message<TransactionalEmailPaginationResp> {
  /**
   *
   * @description Number of records returned in the current response slice.
   *
   * @example 50
   *
   * @generated from field: uint64 count = 1;
   */
  count = protoInt64.zero;

  /**
   *
   * @description The offset provided in the request.
   *
   * @example 0
   *
   * @generated from field: uint64 offset = 2;
   */
  offset = protoInt64.zero;

  /**
   *
   * @description The total number of records matching the criteria.
   *
   * @example 1250
   *
   * @generated from field: uint64 total = 3;
   */
  total = protoInt64.zero;

  /**
   *
   * @description The array of records for the current page.
   *
   * @generated from field: repeated Scailo.TransactionalEmail payload = 4;
   */
  payload: TransactionalEmail[] = [];

  constructor(data?: PartialMessage<TransactionalEmailPaginationResp>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailPaginationResp";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "count", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "offset", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "total", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "payload", kind: "message", T: TransactionalEmail, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailPaginationResp {
    return new TransactionalEmailPaginationResp().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailPaginationResp {
    return new TransactionalEmailPaginationResp().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailPaginationResp {
    return new TransactionalEmailPaginationResp().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailPaginationResp | PlainMessage<TransactionalEmailPaginationResp> | undefined, b: TransactionalEmailPaginationResp | PlainMessage<TransactionalEmailPaginationResp> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailPaginationResp, a, b);
  }
}

/**
 *
 * Describes a pagination request to retrieve records
 *
 * @generated from message Scailo.TransactionalEmailsServicePaginationReq
 */
export class TransactionalEmailsServicePaginationReq extends Message<TransactionalEmailsServicePaginationReq> {
  /**
   *
   * @optional
   *
   * @description Filter by active status. If `true`, then returns only active records. If `false`, then returns only inactive records.
   *
   * @example ANY
   *
   * @generated from field: Scailo.BOOL_FILTER is_active = 1;
   */
  isActive = BOOL_FILTER.BOOL_FILTER_ANY_UNSPECIFIED;

  /**
   *
   * @mandatory
   *
   * @description Number of records to return per page.
   *
   * @example 50
   *
   * @regex ^[1-9][0-9]*$
   *
   * @format Must be a strictly positive integer (1 or greater).
   *
   * @generated from field: int64 count = 2;
   */
  count = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Number of records to skip (offset) for pagination.
   *
   * @example 0
   *
   * @regex ^[0-9]+$
   *
   * @format Non-negative integer.
   *
   * @generated from field: uint64 offset = 3;
   */
  offset = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Sort direction.
   *
   * @example DESCENDING
   *
   * @generated from field: Scailo.SORT_ORDER sort_order = 4;
   */
  sortOrder = SORT_ORDER.ASCENDING_UNSPECIFIED;

  /**
   *
   * @optional
   *
   * @description The specific field key to sort the results by.
   *
   * @generated from field: Scailo.TRANSACTIONAL_EMAIL_SORT_KEY sort_key = 5;
   */
  sortKey = TRANSACTIONAL_EMAIL_SORT_KEY.TRANSACTIONAL_EMAIL_SORT_KEY_ID_UNSPECIFIED;

  constructor(data?: PartialMessage<TransactionalEmailsServicePaginationReq>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailsServicePaginationReq";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "is_active", kind: "enum", T: proto3.getEnumType(BOOL_FILTER) },
    { no: 2, name: "count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "offset", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "sort_order", kind: "enum", T: proto3.getEnumType(SORT_ORDER) },
    { no: 5, name: "sort_key", kind: "enum", T: proto3.getEnumType(TRANSACTIONAL_EMAIL_SORT_KEY) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailsServicePaginationReq {
    return new TransactionalEmailsServicePaginationReq().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailsServicePaginationReq {
    return new TransactionalEmailsServicePaginationReq().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailsServicePaginationReq {
    return new TransactionalEmailsServicePaginationReq().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailsServicePaginationReq | PlainMessage<TransactionalEmailsServicePaginationReq> | undefined, b: TransactionalEmailsServicePaginationReq | PlainMessage<TransactionalEmailsServicePaginationReq> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailsServicePaginationReq, a, b);
  }
}

/**
 *
 * Describes the base request payload of a filter search
 *
 * @generated from message Scailo.TransactionalEmailsServiceFilterReq
 */
export class TransactionalEmailsServiceFilterReq extends Message<TransactionalEmailsServiceFilterReq> {
  /**
   *
   * @optional
   *
   * @description Filter by active status. If `true`, then returns only active records. If `false`, then returns only inactive records.
   *
   * @example ANY
   *
   * @generated from field: Scailo.BOOL_FILTER is_active = 1;
   */
  isActive = BOOL_FILTER.BOOL_FILTER_ANY_UNSPECIFIED;

  /**
   *
   * @mandatory
   *
   * @description Number of records to fetch. **Critical:** Use `-1` to retrieve all records. A value of `0` will return no results. Default is `0`.
   *
   * @example 100
   *
   * @regex ^(?:-1|0|[1-9][0-9]*)$
   *
   * @format Must be -1 or any non-negative integer (>= -1).
   *
   * @generated from field: int64 count = 2;
   */
  count = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Number of records to skip (offset) for pagination.
   *
   * @example 0
   *
   * @regex ^[0-9]+$
   *
   * @format Non-negative integer.
   *
   * @generated from field: uint64 offset = 3;
   */
  offset = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Sort direction.
   *
   * @example DESCENDING
   *
   * @generated from field: Scailo.SORT_ORDER sort_order = 4;
   */
  sortOrder = SORT_ORDER.ASCENDING_UNSPECIFIED;

  /**
   *
   * @optional
   *
   * @description The field used for sorting.
   *
   * @generated from field: Scailo.TRANSACTIONAL_EMAIL_SORT_KEY sort_key = 5;
   */
  sortKey = TRANSACTIONAL_EMAIL_SORT_KEY.TRANSACTIONAL_EMAIL_SORT_KEY_ID_UNSPECIFIED;

  /**
   *
   * @optional
   *
   * @description Filter records created ON or AFTER this UNIX timestamp.
   *
   * @example 1672531200
   *
   * @regex ^[0-9]+$
   *
   * @format Non-negative integer.
   *
   * @generated from field: uint64 creation_timestamp_start = 101;
   */
  creationTimestampStart = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Filter records created ON or BEFORE this UNIX timestamp.
   *
   * @example 1704067199
   *
   * @regex ^[0-9]+$
   *
   * @format Non-negative integer.
   *
   * @generated from field: uint64 creation_timestamp_end = 102;
   */
  creationTimestampEnd = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Filter records modified ON or AFTER this UNIX timestamp.
   *
   * @example 1672531200
   *
   * @regex ^[0-9]+$
   *
   * @format Non-negative integer.
   *
   * @generated from field: uint64 modification_timestamp_start = 103;
   */
  modificationTimestampStart = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Filter records modified ON or BEFORE this UNIX timestamp.
   *
   * @example 1704067199
   *
   * @regex ^[0-9]+$
   *
   * @format Non-negative integer.
   *
   * @generated from field: uint64 modification_timestamp_end = 104;
   */
  modificationTimestampEnd = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Filter by the organization UUID.
   *
   * @example "550e8400-e29b-41d4-a716-446655440000"
   *
   * @regex ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
   *
   * @format If provided, must be a valid v4 UUID in canonical hyphenated form.
   *
   * @generated from field: string entity_uuid = 8;
   */
  entityUuid = "";

  /**
   * Stores the name of the sender
   *
   * @generated from field: string sender_name = 20;
   */
  senderName = "";

  /**
   * Stores the title of the transactional email
   *
   * @generated from field: string title = 21;
   */
  title = "";

  /**
   * Stores the email address to which the reply could be sent
   *
   * @generated from field: string reply_to = 22;
   */
  replyTo = "";

  /**
   * Stores the subject of the transactional email
   *
   * @generated from field: string subject = 23;
   */
  subject = "";

  /**
   * Stores the email address of the recipient
   *
   * @generated from field: string recipient_email_address = 40;
   */
  recipientEmailAddress = "";

  constructor(data?: PartialMessage<TransactionalEmailsServiceFilterReq>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailsServiceFilterReq";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "is_active", kind: "enum", T: proto3.getEnumType(BOOL_FILTER) },
    { no: 2, name: "count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "offset", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "sort_order", kind: "enum", T: proto3.getEnumType(SORT_ORDER) },
    { no: 5, name: "sort_key", kind: "enum", T: proto3.getEnumType(TRANSACTIONAL_EMAIL_SORT_KEY) },
    { no: 101, name: "creation_timestamp_start", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 102, name: "creation_timestamp_end", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 103, name: "modification_timestamp_start", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 104, name: "modification_timestamp_end", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 8, name: "entity_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 20, name: "sender_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 21, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 22, name: "reply_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 23, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 40, name: "recipient_email_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailsServiceFilterReq {
    return new TransactionalEmailsServiceFilterReq().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceFilterReq {
    return new TransactionalEmailsServiceFilterReq().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceFilterReq {
    return new TransactionalEmailsServiceFilterReq().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailsServiceFilterReq | PlainMessage<TransactionalEmailsServiceFilterReq> | undefined, b: TransactionalEmailsServiceFilterReq | PlainMessage<TransactionalEmailsServiceFilterReq> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailsServiceFilterReq, a, b);
  }
}

/**
 *
 * Describes the base request payload of a count search
 *
 * @generated from message Scailo.TransactionalEmailsServiceCountReq
 */
export class TransactionalEmailsServiceCountReq extends Message<TransactionalEmailsServiceCountReq> {
  /**
   *
   * @optional
   *
   * @description Filter by active status. If `true`, then returns only active records. If `false`, then returns only inactive records.
   *
   * @example ANY
   *
   * @generated from field: Scailo.BOOL_FILTER is_active = 1;
   */
  isActive = BOOL_FILTER.BOOL_FILTER_ANY_UNSPECIFIED;

  /**
   *
   * @optional
   *
   * @description Filter records created ON or AFTER this UNIX timestamp.
   *
   * @example 1672531200
   *
   * @regex ^[0-9]+$
   *
   * @format Non-negative integer.
   *
   * @generated from field: uint64 creation_timestamp_start = 101;
   */
  creationTimestampStart = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Filter records created ON or BEFORE this UNIX timestamp.
   *
   * @example 1704067199
   *
   * @regex ^[0-9]+$
   *
   * @format Non-negative integer.
   *
   * @generated from field: uint64 creation_timestamp_end = 102;
   */
  creationTimestampEnd = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Filter records modified ON or AFTER this UNIX timestamp.
   *
   * @example 1672531200
   *
   * @regex ^[0-9]+$
   *
   * @format Non-negative integer.
   *
   * @generated from field: uint64 modification_timestamp_start = 103;
   */
  modificationTimestampStart = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Filter records modified ON or BEFORE this UNIX timestamp.
   *
   * @example 1704067199
   *
   * @regex ^[0-9]+$
   *
   * @format Non-negative integer.
   *
   * @generated from field: uint64 modification_timestamp_end = 104;
   */
  modificationTimestampEnd = protoInt64.zero;

  /**
   *
   * @optional
   *
   * @description Filter by the organization UUID.
   *
   * @example "550e8400-e29b-41d4-a716-446655440000"
   *
   * @regex ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
   *
   * @format If provided, must be a valid v4 UUID in canonical hyphenated form.
   *
   * @generated from field: string entity_uuid = 8;
   */
  entityUuid = "";

  /**
   * Stores the name of the sender
   *
   * @generated from field: string sender_name = 20;
   */
  senderName = "";

  /**
   * Stores the title of the transactional email
   *
   * @generated from field: string title = 21;
   */
  title = "";

  /**
   * Stores the email address to which the reply could be sent
   *
   * @generated from field: string reply_to = 22;
   */
  replyTo = "";

  /**
   * Stores the subject of the transactional email
   *
   * @generated from field: string subject = 23;
   */
  subject = "";

  /**
   * Stores the email address of the recipient
   *
   * @generated from field: string recipient_email_address = 40;
   */
  recipientEmailAddress = "";

  constructor(data?: PartialMessage<TransactionalEmailsServiceCountReq>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailsServiceCountReq";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "is_active", kind: "enum", T: proto3.getEnumType(BOOL_FILTER) },
    { no: 101, name: "creation_timestamp_start", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 102, name: "creation_timestamp_end", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 103, name: "modification_timestamp_start", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 104, name: "modification_timestamp_end", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 8, name: "entity_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 20, name: "sender_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 21, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 22, name: "reply_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 23, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 40, name: "recipient_email_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailsServiceCountReq {
    return new TransactionalEmailsServiceCountReq().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceCountReq {
    return new TransactionalEmailsServiceCountReq().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceCountReq {
    return new TransactionalEmailsServiceCountReq().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailsServiceCountReq | PlainMessage<TransactionalEmailsServiceCountReq> | undefined, b: TransactionalEmailsServiceCountReq | PlainMessage<TransactionalEmailsServiceCountReq> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailsServiceCountReq, a, b);
  }
}

/**
 *
 * Describes the request payload for performing a generic search operation on transactional emails
 *
 * @generated from message Scailo.TransactionalEmailsServiceSearchAllReq
 */
export class TransactionalEmailsServiceSearchAllReq extends Message<TransactionalEmailsServiceSearchAllReq> {
  /**
   *
   * @optional
   *
   * @description Filter by active status. If `true`, then returns only active records. If `false`, then returns only inactive records.
   *
   * @example ANY
   *
   * @generated from field: Scailo.BOOL_FILTER is_active = 1;
   */
  isActive = BOOL_FILTER.BOOL_FILTER_ANY_UNSPECIFIED;

  /**
   * The number of records that need to be sent in the response. Returns all records if it is set to -1
   *
   * @generated from field: int64 count = 2;
   */
  count = protoInt64.zero;

  /**
   * The number that need to be offset by before fetching the records
   *
   * @generated from field: uint64 offset = 3;
   */
  offset = protoInt64.zero;

  /**
   * The sort order that is to be used to fetch the pagination response
   *
   * @generated from field: Scailo.SORT_ORDER sort_order = 4;
   */
  sortOrder = SORT_ORDER.ASCENDING_UNSPECIFIED;

  /**
   * The sort key that is to be used to fetch the response
   *
   * @generated from field: Scailo.TRANSACTIONAL_EMAIL_SORT_KEY sort_key = 5;
   */
  sortKey = TRANSACTIONAL_EMAIL_SORT_KEY.TRANSACTIONAL_EMAIL_SORT_KEY_ID_UNSPECIFIED;

  /**
   *
   * @optional
   *
   * @description Filter by the organization UUID.
   *
   * @example "550e8400-e29b-41d4-a716-446655440000"
   *
   * @regex ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
   *
   * @format If provided, must be a valid v4 UUID in canonical hyphenated form.
   *
   * @generated from field: string entity_uuid = 6;
   */
  entityUuid = "";

  /**
   * Describes the key with which the search operation needs to be performed
   *
   * @generated from field: string search_key = 10;
   */
  searchKey = "";

  constructor(data?: PartialMessage<TransactionalEmailsServiceSearchAllReq>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailsServiceSearchAllReq";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "is_active", kind: "enum", T: proto3.getEnumType(BOOL_FILTER) },
    { no: 2, name: "count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "offset", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "sort_order", kind: "enum", T: proto3.getEnumType(SORT_ORDER) },
    { no: 5, name: "sort_key", kind: "enum", T: proto3.getEnumType(TRANSACTIONAL_EMAIL_SORT_KEY) },
    { no: 6, name: "entity_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "search_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailsServiceSearchAllReq {
    return new TransactionalEmailsServiceSearchAllReq().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceSearchAllReq {
    return new TransactionalEmailsServiceSearchAllReq().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceSearchAllReq {
    return new TransactionalEmailsServiceSearchAllReq().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailsServiceSearchAllReq | PlainMessage<TransactionalEmailsServiceSearchAllReq> | undefined, b: TransactionalEmailsServiceSearchAllReq | PlainMessage<TransactionalEmailsServiceSearchAllReq> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailsServiceSearchAllReq, a, b);
  }
}

/**
 *
 * Describes the necessary data structure during addition of a recipient
 *
 * @generated from message Scailo.TransactionalEmailsServiceAddRecipientRequest
 */
export class TransactionalEmailsServiceAddRecipientRequest extends Message<TransactionalEmailsServiceAddRecipientRequest> {
  /**
   * Stores the email address of the recipient
   *
   * @generated from field: string address = 10;
   */
  address = "";

  constructor(data?: PartialMessage<TransactionalEmailsServiceAddRecipientRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailsServiceAddRecipientRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 10, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailsServiceAddRecipientRequest {
    return new TransactionalEmailsServiceAddRecipientRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceAddRecipientRequest {
    return new TransactionalEmailsServiceAddRecipientRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceAddRecipientRequest {
    return new TransactionalEmailsServiceAddRecipientRequest().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailsServiceAddRecipientRequest | PlainMessage<TransactionalEmailsServiceAddRecipientRequest> | undefined, b: TransactionalEmailsServiceAddRecipientRequest | PlainMessage<TransactionalEmailsServiceAddRecipientRequest> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailsServiceAddRecipientRequest, a, b);
  }
}

/**
 *
 * Describes the data structure that stores the recipient information of a transactional email
 *
 * @generated from message Scailo.TransactionalEmailRecipient
 */
export class TransactionalEmailRecipient extends Message<TransactionalEmailRecipient> {
  /**
   *
   * @description The organization's globally unique identifier.
   *
   * @example "550e8400-e29b-41d4-a716-446655440000"
   *
   * @generated from field: string entity_uuid = 1;
   */
  entityUuid = "";

  /**
   * Stores the metadata of this client
   *
   * @generated from field: Scailo.EmployeeMetadata metadata = 2;
   */
  metadata?: EmployeeMetadata;

  /**
   * The ID of the transactional email
   *
   * @generated from field: uint64 transactional_email_id = 10;
   */
  transactionalEmailId = protoInt64.zero;

  /**
   * The email address of the recipient
   *
   * @generated from field: string address = 11;
   */
  address = "";

  constructor(data?: PartialMessage<TransactionalEmailRecipient>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailRecipient";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entity_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "metadata", kind: "message", T: EmployeeMetadata },
    { no: 10, name: "transactional_email_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 11, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailRecipient {
    return new TransactionalEmailRecipient().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailRecipient {
    return new TransactionalEmailRecipient().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailRecipient {
    return new TransactionalEmailRecipient().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailRecipient | PlainMessage<TransactionalEmailRecipient> | undefined, b: TransactionalEmailRecipient | PlainMessage<TransactionalEmailRecipient> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailRecipient, a, b);
  }
}

/**
 *
 * Describes the message consisting of the list of transactional email recipients
 *
 * @generated from message Scailo.TransactionalEmailRecipientsList
 */
export class TransactionalEmailRecipientsList extends Message<TransactionalEmailRecipientsList> {
  /**
   * List of records
   *
   * @generated from field: repeated Scailo.TransactionalEmailRecipient list = 1;
   */
  list: TransactionalEmailRecipient[] = [];

  constructor(data?: PartialMessage<TransactionalEmailRecipientsList>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailRecipientsList";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: TransactionalEmailRecipient, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailRecipientsList {
    return new TransactionalEmailRecipientsList().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailRecipientsList {
    return new TransactionalEmailRecipientsList().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailRecipientsList {
    return new TransactionalEmailRecipientsList().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailRecipientsList | PlainMessage<TransactionalEmailRecipientsList> | undefined, b: TransactionalEmailRecipientsList | PlainMessage<TransactionalEmailRecipientsList> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailRecipientsList, a, b);
  }
}

/**
 *
 * Describes the necessary data structure during addition of a recipient
 *
 * @generated from message Scailo.TransactionalEmailsServiceAddAttachmentRequest
 */
export class TransactionalEmailsServiceAddAttachmentRequest extends Message<TransactionalEmailsServiceAddAttachmentRequest> {
  /**
   * Stores the name of the attachment
   *
   * @generated from field: string name = 10;
   */
  name = "";

  /**
   * Stores the content of the attachment
   *
   * @generated from field: bytes content = 11;
   */
  content = new Uint8Array(0);

  constructor(data?: PartialMessage<TransactionalEmailsServiceAddAttachmentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailsServiceAddAttachmentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 10, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "content", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailsServiceAddAttachmentRequest {
    return new TransactionalEmailsServiceAddAttachmentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceAddAttachmentRequest {
    return new TransactionalEmailsServiceAddAttachmentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailsServiceAddAttachmentRequest {
    return new TransactionalEmailsServiceAddAttachmentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailsServiceAddAttachmentRequest | PlainMessage<TransactionalEmailsServiceAddAttachmentRequest> | undefined, b: TransactionalEmailsServiceAddAttachmentRequest | PlainMessage<TransactionalEmailsServiceAddAttachmentRequest> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailsServiceAddAttachmentRequest, a, b);
  }
}

/**
 *
 * Describes the data structure that stores the attachment information of a transactional email
 *
 * @generated from message Scailo.TransactionalEmailAttachment
 */
export class TransactionalEmailAttachment extends Message<TransactionalEmailAttachment> {
  /**
   *
   * @description The organization's globally unique identifier.
   *
   * @example "550e8400-e29b-41d4-a716-446655440000"
   *
   * @generated from field: string entity_uuid = 1;
   */
  entityUuid = "";

  /**
   * Stores the metadata of this client
   *
   * @generated from field: Scailo.EmployeeMetadata metadata = 2;
   */
  metadata?: EmployeeMetadata;

  /**
   * The ID of the transactional email
   *
   * @generated from field: uint64 transactional_email_id = 10;
   */
  transactionalEmailId = protoInt64.zero;

  /**
   * The name of the attachment
   *
   * @generated from field: string name = 11;
   */
  name = "";

  /**
   * The content of the attachment
   *
   * @generated from field: bytes content = 12;
   */
  content = new Uint8Array(0);

  constructor(data?: PartialMessage<TransactionalEmailAttachment>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailAttachment";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entity_uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "metadata", kind: "message", T: EmployeeMetadata },
    { no: 10, name: "transactional_email_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 11, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "content", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailAttachment {
    return new TransactionalEmailAttachment().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailAttachment {
    return new TransactionalEmailAttachment().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailAttachment {
    return new TransactionalEmailAttachment().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailAttachment | PlainMessage<TransactionalEmailAttachment> | undefined, b: TransactionalEmailAttachment | PlainMessage<TransactionalEmailAttachment> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailAttachment, a, b);
  }
}

/**
 *
 * Describes the message consisting of the list of transactional email attachments
 *
 * @generated from message Scailo.TransactionalEmailAttachmentsList
 */
export class TransactionalEmailAttachmentsList extends Message<TransactionalEmailAttachmentsList> {
  /**
   * List of records
   *
   * @generated from field: repeated Scailo.TransactionalEmailAttachment list = 1;
   */
  list: TransactionalEmailAttachment[] = [];

  constructor(data?: PartialMessage<TransactionalEmailAttachmentsList>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Scailo.TransactionalEmailAttachmentsList";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "list", kind: "message", T: TransactionalEmailAttachment, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TransactionalEmailAttachmentsList {
    return new TransactionalEmailAttachmentsList().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TransactionalEmailAttachmentsList {
    return new TransactionalEmailAttachmentsList().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TransactionalEmailAttachmentsList {
    return new TransactionalEmailAttachmentsList().fromJsonString(jsonString, options);
  }

  static equals(a: TransactionalEmailAttachmentsList | PlainMessage<TransactionalEmailAttachmentsList> | undefined, b: TransactionalEmailAttachmentsList | PlainMessage<TransactionalEmailAttachmentsList> | undefined): boolean {
    return proto3.util.equals(TransactionalEmailAttachmentsList, a, b);
  }
}

