// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file work_orders.scailo.proto (package Scailo, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { WorkOrder, WorkOrderAncillaryParameters, WorkOrderItem, WorkOrderItemHistoryRequest, WorkOrderItemProspectiveInfoRequest, WorkOrderItemsSearchRequest, WorkOrderProductionStatisticsList, WorkOrderRequirementStatisticsList, WorkOrdersItemsList, WorkOrdersList, WorkOrdersServiceAutofillRequest, WorkOrdersServiceCountReq, WorkOrdersServiceCreateRequest, WorkOrdersServiceFilterReq, WorkOrdersServiceItemCreateRequest, WorkOrdersServiceItemUpdateRequest, WorkOrdersServicePaginatedItemsResponse, WorkOrdersServicePaginationReq, WorkOrdersServicePaginationResponse, WorkOrdersServiceSearchAllReq, WorkOrdersServiceUpdateRequest } from "./work_orders.scailo_pb.js";
import { ActiveStatus, AmendmentLogsList, BooleanResponse, CountInSLCStatusRequest, CountResponse, Empty, Identifier, IdentifierResponse, IdentifiersList, IdentifierUUID, IdentifierUUIDWithFile, IdentifierUUIDWithUserComment, IdentifierWithEmailAttributes, IdentifierWithSearchKey, IdentifierWithUserComment, ReorderItemsRequest, RepeatWithDeliveryDate, SimpleSearchReq, StandardFile } from "./base.scailo_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { MagicLink, MagicLinksServiceCreateRequestForSpecificResource } from "./magic_links.scailo_pb.js";
import { FamiliesList, FilterFamiliesReqForIdentifier } from "./families.scailo_pb.js";

/**
 *
 * Describes the common methods applicable on each work order
 *
 * @generated from service Scailo.WorkOrdersService
 */
export const WorkOrdersService = {
  typeName: "Scailo.WorkOrdersService",
  methods: {
    /**
     * Create and send for verification
     *
     * @generated from rpc Scailo.WorkOrdersService.Create
     */
    create: {
      name: "Create",
      I: WorkOrdersServiceCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Saves a new record as a draft without triggering side effects.
     *
     * Use this method when you have incomplete information but wish to persist
     * the record for later completion. The record remains in a `DRAFT` state.
     *
     * **Note:** Some strict validation rules may be relaxed in the backend for drafts compared to `Create`.
     *
     * **Side Effects:**
     * - Generates a unique system UUID.
     * - Records an audit log for the "Draft" action.
     *
     * **Errors:**
     * - `INVALID_ARGUMENT`: If critical system fields are missing.
     *
     * @generated from rpc Scailo.WorkOrdersService.Draft
     */
    draft: {
      name: "Draft",
      I: WorkOrdersServiceCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates an existing record that is currently in `DRAFT` status.
     *
     * This method allows modification of all primary attributes while the record is not yet verified.
     *
     * **Errors:**
     * - `FAILED_PRECONDITION`: If the record is not in a `DRAFT` state.
     * - `NOT_FOUND`: If the provided ID does not exist.
     *
     * @generated from rpc Scailo.WorkOrdersService.DraftUpdate
     */
    draftUpdate: {
      name: "DraftUpdate",
      I: WorkOrdersServiceUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Submits a record in `DRAFT` or `REVISION` status for verification.
     *
     * This triggers the first stage of the approval workflow.
     *
     * **Status Transition:** -> `PREVERIFY`
     *
     * **Side Effects:**
     * - Notifies designated verifiers or approvers.
     * - Locks certain fields from being updated without returning to `REVISION`.
     *
     * @generated from rpc Scailo.WorkOrdersService.SendForVerification
     */
    sendForVerification: {
      name: "SendForVerification",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Marks a record as verified, signaling that it is ready for final approval.
     *
     * **Status Transition:** -> `VERIFIED`
     *
     * **Side Effects:**
     * - Records the verifying user and timestamp in the audit logs.
     *
     * @generated from rpc Scailo.WorkOrdersService.Verify
     */
    verify: {
      name: "Verify",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Officially approves the record.
     *
     * **Status Transition:** -> `STANDING`
     *
     * **Side Effects:**
     * - Finalizes the `final_ref_number`.
     * - Records the approver's identity and timestamp.
     *
     * @generated from rpc Scailo.WorkOrdersService.Approve
     */
    approve: {
      name: "Approve",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sends the record back to the creator for corrections.
     *
     * Use this if details are incorrect or supporting documents (in the vault) are missing.
     *
     * **Status Transition:** -> `REVISION`
     *
     * **Side Effects:**
     * - Notifies the record creator that changes are required.
     *
     * @generated from rpc Scailo.WorkOrdersService.SendForRevision
     */
    sendForRevision: {
      name: "SendForRevision",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a record that has been sent back for `REVISION`.
     *
     * **Side Effects:**
     * - Re-validates the updated fields.
     *
     * @generated from rpc Scailo.WorkOrdersService.RevisionUpdate
     */
    revisionUpdate: {
      name: "RevisionUpdate",
      I: WorkOrdersServiceUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Temporarily halts processing of the record.
     *
     * **Status Transition:** -> `HALTED`
     *
     * @generated from rpc Scailo.WorkOrdersService.Halt
     */
    halt: {
      name: "Halt",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Permanently cancels the record.
     *
     * Records in this state are typically ignored.
     *
     * **Status Transition:** -> `DISCARDED`
     *
     * @generated from rpc Scailo.WorkOrdersService.Discard
     */
    discard: {
      name: "Discard",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Restores a previously `DISCARDED` or `HALTED` record.
     *
     * **Side Effects:**
     * - Moves the record back to `PREVERIFY` and sends for verification.
     *
     * @generated from rpc Scailo.WorkOrdersService.Restore
     */
    restore: {
      name: "Restore",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Marks the record as finalized and fully processed.
     *
     * **Status Transition:** -> `COMPLETED`
     *
     * **Side Effects:**
     * - Locks the record from further modification.
     *
     * @generated from rpc Scailo.WorkOrdersService.Complete
     */
    complete: {
      name: "Complete",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Repeat
     *
     * @generated from rpc Scailo.WorkOrdersService.Repeat
     */
    repeat: {
      name: "Repeat",
      I: RepeatWithDeliveryDate,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reopen
     *
     * @generated from rpc Scailo.WorkOrdersService.Reopen
     */
    reopen: {
      name: "Reopen",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds an audit comment to the record's history without changing its current lifecycle status.
     *
     * @generated from rpc Scailo.WorkOrdersService.CommentAdd
     */
    commentAdd: {
      name: "CommentAdd",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Send Email
     *
     * @generated from rpc Scailo.WorkOrdersService.SendEmail
     */
    sendEmail: {
      name: "SendEmail",
      I: IdentifierWithEmailAttributes,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Generates a magic link for temporary, authenticated access to the resource.
     *
     * This enables non-system users (or users without active sessions) to view specific details.
     *
     * @generated from rpc Scailo.WorkOrdersService.CreateMagicLink
     */
    createMagicLink: {
      name: "CreateMagicLink",
      I: MagicLinksServiceCreateRequestForSpecificResource,
      O: MagicLink,
      kind: MethodKind.Unary,
    },
    /**
     * Autofill the work order
     *
     * @generated from rpc Scailo.WorkOrdersService.Autofill
     */
    autofill: {
      name: "Autofill",
      I: WorkOrdersServiceAutofillRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Amend the work order and send for revision
     *
     * @generated from rpc Scailo.WorkOrdersService.Amend
     */
    amend: {
      name: "Amend",
      I: IdentifierUUIDWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Checks if the Work Order can be marked as completed
     *
     * @generated from rpc Scailo.WorkOrdersService.IsCompletable
     */
    isCompletable: {
      name: "IsCompletable",
      I: IdentifierUUID,
      O: BooleanResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Add an item to a work order
     *
     * @generated from rpc Scailo.WorkOrdersService.AddWorkOrderItem
     */
    addWorkOrderItem: {
      name: "AddWorkOrderItem",
      I: WorkOrdersServiceItemCreateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Modify an item in a work order
     *
     * @generated from rpc Scailo.WorkOrdersService.ModifyWorkOrderItem
     */
    modifyWorkOrderItem: {
      name: "ModifyWorkOrderItem",
      I: WorkOrdersServiceItemUpdateRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Approve an item in a work order
     *
     * @generated from rpc Scailo.WorkOrdersService.ApproveWorkOrderItem
     */
    approveWorkOrderItem: {
      name: "ApproveWorkOrderItem",
      I: IdentifierWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete an item in a work order
     *
     * @generated from rpc Scailo.WorkOrdersService.DeleteWorkOrderItem
     */
    deleteWorkOrderItem: {
      name: "DeleteWorkOrderItem",
      I: IdentifierWithUserComment,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reorder items in a work order
     *
     * @generated from rpc Scailo.WorkOrdersService.ReorderWorkOrderItems
     */
    reorderWorkOrderItems: {
      name: "ReorderWorkOrderItems",
      I: ReorderItemsRequest,
      O: IdentifierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View Work Order Item by ID
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewWorkOrderItemByID
     */
    viewWorkOrderItemByID: {
      name: "ViewWorkOrderItemByID",
      I: Identifier,
      O: WorkOrderItem,
      kind: MethodKind.Unary,
    },
    /**
     * View approved work order items for given work order ID
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewApprovedWorkOrderItems
     */
    viewApprovedWorkOrderItems: {
      name: "ViewApprovedWorkOrderItems",
      I: IdentifierWithSearchKey,
      O: WorkOrdersItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * View unapproved work order items for given work order ID
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewUnapprovedWorkOrderItems
     */
    viewUnapprovedWorkOrderItems: {
      name: "ViewUnapprovedWorkOrderItems",
      I: IdentifierWithSearchKey,
      O: WorkOrdersItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * View the history of the work order item
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewWorkOrderItemHistory
     */
    viewWorkOrderItemHistory: {
      name: "ViewWorkOrderItemHistory",
      I: WorkOrderItemHistoryRequest,
      O: WorkOrdersItemsList,
      kind: MethodKind.Unary,
    },
    /**
     * View approved work order items for given work order ID with pagination
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewPaginatedApprovedWorkOrderItems
     */
    viewPaginatedApprovedWorkOrderItems: {
      name: "ViewPaginatedApprovedWorkOrderItems",
      I: WorkOrderItemsSearchRequest,
      O: WorkOrdersServicePaginatedItemsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View unapproved work order items for given work order ID with pagination
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewPaginatedUnapprovedWorkOrderItems
     */
    viewPaginatedUnapprovedWorkOrderItems: {
      name: "ViewPaginatedUnapprovedWorkOrderItems",
      I: WorkOrderItemsSearchRequest,
      O: WorkOrdersServicePaginatedItemsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Search through work order items with pagination
     *
     * @generated from rpc Scailo.WorkOrdersService.SearchItemsWithPagination
     */
    searchItemsWithPagination: {
      name: "SearchItemsWithPagination",
      I: WorkOrderItemsSearchRequest,
      O: WorkOrdersServicePaginatedItemsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CSV operations
     * Download the CSV file with the associated line items. The same file could then be used to upload line items.
     *
     * @generated from rpc Scailo.WorkOrdersService.DownloadItemsAsCSV
     */
    downloadItemsAsCSV: {
      name: "DownloadItemsAsCSV",
      I: IdentifierUUID,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
    /**
     * Download the CSV template that could be used to upload items
     *
     * @generated from rpc Scailo.WorkOrdersService.DownloadItemsTemplateAsCSV
     */
    downloadItemsTemplateAsCSV: {
      name: "DownloadItemsTemplateAsCSV",
      I: Empty,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
    /**
     * Upload items using a CSV file. This is an idempotent operation. All the existing items are deleted before adding the items from the file.
     *
     * @generated from rpc Scailo.WorkOrdersService.UploadWorkOrderItems
     */
    uploadWorkOrderItems: {
      name: "UploadWorkOrderItems",
      I: IdentifierUUIDWithFile,
      O: IdentifiersList,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a single record by its internal numeric ID. This operation is optimized for high-performance internal system logic and backend-to-backend communication
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewByID
     */
    viewByID: {
      name: "ViewByID",
      I: Identifier,
      O: WorkOrder,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a single record by its globally unique UUID. This is intended for public-facing interfaces, since record identifiers aren't sequential and thus cannot be predicted.
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewByUUID
     */
    viewByUUID: {
      name: "ViewByUUID",
      I: IdentifierUUID,
      O: WorkOrder,
      kind: MethodKind.Unary,
    },
    /**
     * View by Reference ID (returns the latest record in case of duplicates)
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewByReferenceID
     */
    viewByReferenceID: {
      name: "ViewByReferenceID",
      I: SimpleSearchReq,
      O: WorkOrder,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a record by ID excluding high-volume fields like logs for performance. This operation is optimized for high-performance internal system logic and backend-to-backend communication
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewEssentialByID
     */
    viewEssentialByID: {
      name: "ViewEssentialByID",
      I: Identifier,
      O: WorkOrder,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a record by UUID excluding high-volume fields like logs. This is intended for public-facing interfaces, since record identifiers aren't sequential and thus cannot be predicted.
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewEssentialByUUID
     */
    viewEssentialByUUID: {
      name: "ViewEssentialByUUID",
      I: IdentifierUUID,
      O: WorkOrder,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a list of records matching the provided array of internal IDs.
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewFromIDs
     */
    viewFromIDs: {
      name: "ViewFromIDs",
      I: IdentifiersList,
      O: WorkOrdersList,
      kind: MethodKind.Unary,
    },
    /**
     * View the ancillary parameters (UUIDs of the internal references) by UUID
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewAncillaryParametersByUUID
     */
    viewAncillaryParametersByUUID: {
      name: "ViewAncillaryParametersByUUID",
      I: IdentifierUUID,
      O: WorkOrderAncillaryParameters,
      kind: MethodKind.Unary,
    },
    /**
     * Returns all records filtered by their active status.
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewAll
     */
    viewAll: {
      name: "ViewAll",
      I: ActiveStatus,
      O: WorkOrdersList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns all records belonging to a specific organization/entity UUID.
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewAllForEntityUUID
     */
    viewAllForEntityUUID: {
      name: "ViewAllForEntityUUID",
      I: IdentifierUUID,
      O: WorkOrdersList,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a paginated list of records based on status, sort keys, and offsets.
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewWithPagination
     */
    viewWithPagination: {
      name: "ViewWithPagination",
      I: WorkOrdersServicePaginationReq,
      O: WorkOrdersServicePaginationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * View all the amendments made
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewAmendments
     */
    viewAmendments: {
      name: "ViewAmendments",
      I: Identifier,
      O: AmendmentLogsList,
      kind: MethodKind.Unary,
    },
    /**
     * View prospective families for the given work order
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewProspectiveFamilies
     */
    viewProspectiveFamilies: {
      name: "ViewProspectiveFamilies",
      I: IdentifierWithSearchKey,
      O: FamiliesList,
      kind: MethodKind.Unary,
    },
    /**
     * Filter prospective families for the record represented by the given UUID identifier
     *
     * @generated from rpc Scailo.WorkOrdersService.FilterProspectiveFamilies
     */
    filterProspectiveFamilies: {
      name: "FilterProspectiveFamilies",
      I: FilterFamiliesReqForIdentifier,
      O: FamiliesList,
      kind: MethodKind.Unary,
    },
    /**
     * View prospective work order item info for the given family ID and work order ID
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewProspectiveWorkOrderItem
     */
    viewProspectiveWorkOrderItem: {
      name: "ViewProspectiveWorkOrderItem",
      I: WorkOrderItemProspectiveInfoRequest,
      O: WorkOrdersServiceItemCreateRequest,
      kind: MethodKind.Unary,
    },
    /**
     * View requirement statistics (match with the selected sales order) of the work order
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewRequirementStatistics
     */
    viewRequirementStatistics: {
      name: "ViewRequirementStatistics",
      I: IdentifierUUID,
      O: WorkOrderRequirementStatisticsList,
      kind: MethodKind.Unary,
    },
    /**
     * View production statistics (match with all the associated production plans) of the work order
     *
     * @generated from rpc Scailo.WorkOrdersService.ViewProductionStatistics
     */
    viewProductionStatistics: {
      name: "ViewProductionStatistics",
      I: IdentifierUUID,
      O: WorkOrderProductionStatisticsList,
      kind: MethodKind.Unary,
    },
    /**
     * Checks if the record is downloadable (checks if the custom download function has been implemented)
     *
     * @generated from rpc Scailo.WorkOrdersService.IsDownloadable
     */
    isDownloadable: {
      name: "IsDownloadable",
      I: IdentifierUUID,
      O: BooleanResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Download work order with the given IdentifierUUID (can be used to allow public downloads)
     *
     * @generated from rpc Scailo.WorkOrdersService.DownloadByUUID
     */
    downloadByUUID: {
      name: "DownloadByUUID",
      I: IdentifierUUID,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
    /**
     * Performs a free-text search across records using a search key.
     *
     * @generated from rpc Scailo.WorkOrdersService.SearchAll
     */
    searchAll: {
      name: "SearchAll",
      I: WorkOrdersServiceSearchAllReq,
      O: WorkOrdersList,
      kind: MethodKind.Unary,
    },
    /**
     * Performs a high-granularity search based on multiple specific field filters.
     *
     * @generated from rpc Scailo.WorkOrdersService.Filter
     */
    filter: {
      name: "Filter",
      I: WorkOrdersServiceFilterReq,
      O: WorkOrdersList,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the total number of records currently in a specific lifecycle status.
     *
     * @generated from rpc Scailo.WorkOrdersService.CountInStatus
     */
    countInStatus: {
      name: "CountInStatus",
      I: CountInSLCStatusRequest,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns the total count of records matching the given complex filter criteria.
     *
     * @generated from rpc Scailo.WorkOrdersService.Count
     */
    count: {
      name: "Count",
      I: WorkOrdersServiceCountReq,
      O: CountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CSV operations
     * Download the CSV file that consists of the list of records according to the given filter request. The same file could also be used as a template for uploading records
     *
     * @generated from rpc Scailo.WorkOrdersService.DownloadAsCSV
     */
    downloadAsCSV: {
      name: "DownloadAsCSV",
      I: WorkOrdersServiceFilterReq,
      O: StandardFile,
      kind: MethodKind.Unary,
    },
  }
} as const;

